import { Crop, Building, Tech, Achievement, Resources, Animal } from './types'

export const INITIAL_RESOURCES: Resources = {
  gold: 200,
  seeds: 30,
  water: 40,
  fertilizer: 15,
  energy: 150,
  research: 0,
  hay: 15,
  milk: 0,
  eggs: 0,
  wool: 0,
  leather: 0,
  meat: 0,
}

export const CROPS: Crop[] = [
  {
    id: 'wheat',
    name: 'Wheat',
    icon: '🌾',
    description: 'Basic grain crop, fast growing',
    cost: { seeds: 1, water: 2 },
    growTime: 8000,
    yield: { gold: 15, seeds: 2, hay: 2, research: 0.2 },
    unlocked: true,
    tier: 1,
    category: 'grain',
  },
  {
    id: 'corn',
    name: 'Corn',
    icon: '🌽',
    description: 'Staple crop with good yield',
    cost: { seeds: 2, water: 3, fertilizer: 1 },
    growTime: 12000,
    yield: { gold: 30, seeds: 3, hay: 3, research: 0.3 },
    unlocked: true,
    tier: 1,
    category: 'grain',
  },
  {
    id: 'carrot',
    name: 'Carrot',
    icon: '🥕',
    description: 'Root vegetable, moderate value',
    cost: { seeds: 2, water: 3 },
    growTime: 10000,
    yield: { gold: 22, seeds: 2 },
    unlocked: false,
    requiredTech: 'tech_root_crops',
    tier: 2,
    category: 'vegetable',
  },
  {
    id: 'tomato',
    name: 'Tomato',
    icon: '🍅',
    description: 'Valuable fruit, generates research',
    cost: { seeds: 3, water: 4, fertilizer: 2 },
    growTime: 15000,
    yield: { gold: 48, research: 1.5 },
    unlocked: false,
    requiredTech: 'tech_tomatoes',
    tier: 2,
    category: 'vegetable',
  },
  {
    id: 'potato',
    name: 'Potato',
    icon: '🥔',
    description: 'High yield root crop',
    cost: { seeds: 3, water: 4, fertilizer: 1 },
    growTime: 14000,
    yield: { gold: 42, seeds: 4 },
    unlocked: false,
    requiredTech: 'tech_root_crops',
    tier: 2,
    category: 'vegetable',
  },
  {
    id: 'onion',
    name: 'Onion',
    icon: '🧅',
    description: 'Hardy root vegetable, stores well',
    cost: { seeds: 2, water: 3, fertilizer: 1 },
    growTime: 11000,
    yield: { gold: 28, seeds: 2, research: 0.3 },
    unlocked: false,
    requiredTech: 'tech_root_crops',
    tier: 2,
    category: 'vegetable',
  },
  {
    id: 'lettuce',
    name: 'Lettuce',
    icon: '🥬',
    description: 'Fast growing leafy green',
    cost: { seeds: 2, water: 4 },
    growTime: 9000,
    yield: { gold: 20, seeds: 1 },
    unlocked: false,
    requiredTech: 'tech_leafy_greens',
    tier: 2,
    category: 'vegetable',
  },
  {
    id: 'cabbage',
    name: 'Cabbage',
    icon: '🥬',
    description: 'Hearty vegetable, excellent yield',
    cost: { seeds: 3, water: 5, fertilizer: 2 },
    growTime: 16000,
    yield: { gold: 50, seeds: 2, research: 0.5 },
    unlocked: false,
    requiredTech: 'tech_leafy_greens',
    tier: 2,
    category: 'vegetable',
  },
  {
    id: 'strawberry',
    name: 'Strawberry',
    icon: '🍓',
    description: 'Premium berry, high value',
    cost: { seeds: 4, water: 5, fertilizer: 3 },
    growTime: 16000,
    yield: { gold: 70, research: 2 },
    unlocked: false,
    requiredTech: 'tech_berries',
    tier: 3,
    category: 'fruit',
  },
  {
    id: 'blueberry',
    name: 'Blueberry',
    icon: '🫐',
    description: 'Antioxidant-rich berry, good return',
    cost: { seeds: 4, water: 5, fertilizer: 2 },
    growTime: 14000,
    yield: { gold: 60, research: 1.5 },
    unlocked: false,
    requiredTech: 'tech_berries',
    tier: 3,
    category: 'fruit',
  },
  {
    id: 'grapes',
    name: 'Grapes',
    icon: '🍇',
    description: 'Luxury fruit for wine production',
    cost: { seeds: 5, water: 6, fertilizer: 3, energy: 5 },
    growTime: 22000,
    yield: { gold: 105, research: 3 },
    unlocked: false,
    requiredTech: 'tech_fruit_crops',
    tier: 3,
    category: 'fruit',
  },
  {
    id: 'apple',
    name: 'Apple',
    icon: '🍎',
    description: 'Classic orchard fruit, steady income',
    cost: { seeds: 5, water: 5, fertilizer: 3 },
    growTime: 20000,
    yield: { gold: 95, seeds: 1, research: 2.5 },
    unlocked: false,
    requiredTech: 'tech_fruit_crops',
    tier: 3,
    category: 'fruit',
  },
  {
    id: 'peach',
    name: 'Peach',
    icon: '🍑',
    description: 'Juicy stone fruit, premium price',
    cost: { seeds: 6, water: 6, fertilizer: 4, energy: 5 },
    growTime: 24000,
    yield: { gold: 115, research: 3.5 },
    unlocked: false,
    requiredTech: 'tech_fruit_crops',
    tier: 3,
    category: 'fruit',
  },
  {
    id: 'pumpkin',
    name: 'Pumpkin',
    icon: '🎃',
    description: 'Large specialty crop',
    cost: { seeds: 6, water: 7, fertilizer: 4 },
    growTime: 25000,
    yield: { gold: 130, research: 3.5, seeds: 3 },
    unlocked: false,
    requiredTech: 'tech_specialty_crops',
    tier: 3,
    category: 'vegetable',
  },
  {
    id: 'watermelon',
    name: 'Watermelon',
    icon: '🍉',
    description: 'Massive fruit, excellent profit',
    cost: { seeds: 7, water: 10, fertilizer: 5 },
    growTime: 28000,
    yield: { gold: 160, research: 4.5 },
    unlocked: false,
    requiredTech: 'tech_specialty_crops',
    tier: 4,
    category: 'fruit',
  },
  {
    id: 'eggplant',
    name: 'Eggplant',
    icon: '🍆',
    description: 'Versatile vegetable, good market price',
    cost: { seeds: 5, water: 6, fertilizer: 3 },
    growTime: 18000,
    yield: { gold: 85, research: 2 },
    unlocked: false,
    requiredTech: 'tech_specialty_crops',
    tier: 3,
    category: 'vegetable',
  },
  {
    id: 'pepper',
    name: 'Bell Pepper',
    icon: '🫑',
    description: 'Colorful vegetable, consistent yield',
    cost: { seeds: 4, water: 5, fertilizer: 3 },
    growTime: 17000,
    yield: { gold: 78, research: 2 },
    unlocked: false,
    requiredTech: 'tech_tomatoes',
    tier: 2,
    category: 'vegetable',
  },
  {
    id: 'rice',
    name: 'Rice',
    icon: '🌾',
    description: 'Advanced grain, water intensive',
    cost: { seeds: 5, water: 12, fertilizer: 3 },
    growTime: 20000,
    yield: { gold: 95, seeds: 5, hay: 5, research: 1 },
    unlocked: false,
    requiredTech: 'tech_advanced_grains',
    tier: 4,
    category: 'grain',
  },
  {
    id: 'barley',
    name: 'Barley',
    icon: '🌾',
    description: 'Brewing grain, feeds livestock',
    cost: { seeds: 4, water: 5, fertilizer: 2 },
    growTime: 15000,
    yield: { gold: 65, seeds: 4, hay: 6, research: 1 },
    unlocked: false,
    requiredTech: 'tech_advanced_grains',
    tier: 3,
    category: 'grain',
  },
  {
    id: 'oats',
    name: 'Oats',
    icon: '🌾',
    description: 'Nutritious grain for food and feed',
    cost: { seeds: 3, water: 4, fertilizer: 2 },
    growTime: 13000,
    yield: { gold: 55, seeds: 4, hay: 4, research: 0.8 },
    unlocked: false,
    requiredTech: 'tech_advanced_grains',
    tier: 3,
    category: 'grain',
  },
  {
    id: 'sunflower',
    name: 'Sunflower',
    icon: '🌻',
    description: 'Oil seed crop, beautiful flowers',
    cost: { seeds: 5, water: 5, fertilizer: 3, energy: 5 },
    growTime: 21000,
    yield: { gold: 110, seeds: 8, research: 2.5 },
    unlocked: false,
    requiredTech: 'tech_oil_crops',
    tier: 4,
    category: 'grain',
  },
  {
    id: 'soybean',
    name: 'Soybean',
    icon: '🫘',
    description: 'Protein-rich legume, versatile crop',
    cost: { seeds: 4, water: 6, fertilizer: 2 },
    growTime: 18000,
    yield: { gold: 90, seeds: 6, research: 2 },
    unlocked: false,
    requiredTech: 'tech_oil_crops',
    tier: 4,
    category: 'grain',
  },
  {
    id: 'coffee',
    name: 'Coffee',
    icon: '☕',
    description: 'Export crop with premium value',
    cost: { seeds: 8, water: 8, fertilizer: 6, energy: 10 },
    growTime: 35000,
    yield: { gold: 240, research: 7 },
    unlocked: false,
    requiredTech: 'tech_export_crops',
    tier: 5,
    category: 'exotic',
  },
  {
    id: 'cocoa',
    name: 'Cocoa',
    icon: '🍫',
    description: 'Chocolate production, very valuable',
    cost: { seeds: 10, water: 9, fertilizer: 7, energy: 12 },
    growTime: 40000,
    yield: { gold: 320, research: 9 },
    unlocked: false,
    requiredTech: 'tech_export_crops',
    tier: 5,
    category: 'exotic',
  },
  {
    id: 'vanilla',
    name: 'Vanilla',
    icon: '🌸',
    description: 'Rare spice, extremely valuable',
    cost: { seeds: 12, water: 10, fertilizer: 8, energy: 15 },
    growTime: 45000,
    yield: { gold: 380, research: 10 },
    unlocked: false,
    requiredTech: 'tech_spice_crops',
    tier: 5,
    category: 'exotic',
  },
  {
    id: 'saffron',
    name: 'Saffron',
    icon: '🌼',
    description: 'Most expensive spice, requires care',
    cost: { seeds: 15, water: 8, fertilizer: 10, energy: 20 },
    growTime: 50000,
    yield: { gold: 500, research: 12 },
    unlocked: false,
    requiredTech: 'tech_spice_crops',
    tier: 6,
    category: 'exotic',
  },
  {
    id: 'truffle',
    name: 'Truffle',
    icon: '🍄',
    description: 'Luxury fungus, extreme value',
    cost: { seeds: 20, water: 12, fertilizer: 15, energy: 25 },
    growTime: 55000,
    yield: { gold: 650, research: 15 },
    unlocked: false,
    requiredTech: 'tech_luxury_crops',
    tier: 6,
    category: 'exotic',
  },
  {
    id: 'dragon_fruit',
    name: 'Dragon Fruit',
    icon: '🐉',
    description: 'Exotic cactus fruit, striking appearance',
    cost: { seeds: 10, water: 7, fertilizer: 6, energy: 15 },
    growTime: 38000,
    yield: { gold: 280, research: 8 },
    unlocked: false,
    requiredTech: 'tech_exotic_fruits',
    tier: 5,
    category: 'exotic',
  },
  {
    id: 'mango',
    name: 'Mango',
    icon: '🥭',
    description: 'Tropical fruit, sweet and profitable',
    cost: { seeds: 8, water: 9, fertilizer: 5, energy: 10 },
    growTime: 32000,
    yield: { gold: 210, research: 6 },
    unlocked: false,
    requiredTech: 'tech_exotic_fruits',
    tier: 5,
    category: 'exotic',
  },
  {
    id: 'pineapple',
    name: 'Pineapple',
    icon: '🍍',
    description: 'Tropical favorite, long growing time',
    cost: { seeds: 9, water: 10, fertilizer: 6, energy: 12 },
    growTime: 36000,
    yield: { gold: 250, research: 7 },
    unlocked: false,
    requiredTech: 'tech_exotic_fruits',
    tier: 5,
    category: 'exotic',
  },
  {
    id: 'avocado',
    name: 'Avocado',
    icon: '🥑',
    description: 'Creamy fruit, high demand',
    cost: { seeds: 7, water: 7, fertilizer: 5, energy: 8 },
    growTime: 30000,
    yield: { gold: 190, research: 5 },
    unlocked: false,
    requiredTech: 'tech_fruit_crops',
    tier: 4,
    category: 'fruit',
  },
  {
    id: 'cherry',
    name: 'Cherry',
    icon: '🍒',
    description: 'Delicate stone fruit, premium market',
    cost: { seeds: 6, water: 6, fertilizer: 4, energy: 6 },
    growTime: 23000,
    yield: { gold: 125, research: 3.5 },
    unlocked: false,
    requiredTech: 'tech_fruit_crops',
    tier: 3,
    category: 'fruit',
  },
  {
    id: 'mushroom',
    name: 'Gourmet Mushroom',
    icon: '🍄',
    description: 'Specialty fungi, grows in shade',
    cost: { seeds: 8, water: 10, fertilizer: 8, energy: 5 },
    growTime: 26000,
    yield: { gold: 150, research: 4 },
    unlocked: false,
    requiredTech: 'tech_mushroom_cultivation',
    tier: 4,
    category: 'exotic',
  },
  {
    id: 'quinoa',
    name: 'Quinoa',
    icon: '🌾',
    description: 'Superfood grain, health conscious market',
    cost: { seeds: 6, water: 7, fertilizer: 4 },
    growTime: 22000,
    yield: { gold: 120, seeds: 5, research: 3 },
    unlocked: false,
    requiredTech: 'tech_advanced_grains',
    tier: 4,
    category: 'grain',
  },
  {
    id: 'hemp',
    name: 'Hemp',
    icon: '🌿',
    description: 'Multi-purpose industrial crop',
    cost: { seeds: 7, water: 6, fertilizer: 5, energy: 8 },
    growTime: 27000,
    yield: { gold: 160, research: 5, energy: 5 },
    unlocked: false,
    requiredTech: 'tech_industrial_crops',
    tier: 4,
    category: 'grain',
  },
  {
    id: 'cotton',
    name: 'Cotton',
    icon: '☁️',
    description: 'Textile fiber, consistent demand',
    cost: { seeds: 6, water: 8, fertilizer: 4 },
    growTime: 25000,
    yield: { gold: 140, research: 4 },
    unlocked: false,
    requiredTech: 'tech_industrial_crops',
    tier: 4,
    category: 'grain',
  },
  {
    id: 'crystal_grain',
    name: 'Crystal Grain',
    icon: '💎',
    description: 'Bioengineered crop, unmatched value',
    cost: { seeds: 25, water: 20, fertilizer: 20, energy: 40 },
    growTime: 70000,
    yield: { gold: 800, research: 20, seeds: 5 },
    unlocked: false,
    requiredTech: 'tech_bioengineering',
    tier: 6,
    category: 'exotic',
  },
  {
    id: 'golden_wheat',
    name: 'Golden Wheat',
    icon: '✨',
    description: 'Enhanced grain variety, superior yield',
    cost: { seeds: 20, water: 15, fertilizer: 15, energy: 30 },
    growTime: 60000,
    yield: { gold: 650, seeds: 15, hay: 10, research: 18 },
    unlocked: false,
    requiredTech: 'tech_bioengineering',
    tier: 6,
    category: 'exotic',
  },
]

export const ANIMALS: Animal[] = [
  {
    id: 'chicken',
    name: 'Chicken',
    icon: '🐔',
    description: 'Produces eggs regularly',
    cost: { gold: 100, hay: 5 },
    feedCost: { hay: 2, water: 1 },
    feedInterval: 20000,
    production: { eggs: 4, gold: 12 },
    productionInterval: 15000,
    unlocked: true,
    tier: 1,
    category: 'poultry',
  },
  {
    id: 'cow',
    name: 'Cow',
    icon: '🐄',
    description: 'Produces milk and leather',
    cost: { gold: 280, hay: 20 },
    feedCost: { hay: 5, water: 3 },
    feedInterval: 30000,
    production: { milk: 6, gold: 30 },
    productionInterval: 25000,
    unlocked: false,
    requiredTech: 'tech_livestock',
    tier: 2,
    category: 'livestock',
  },
  {
    id: 'sheep',
    name: 'Sheep',
    icon: '🐑',
    description: 'Produces wool for textiles',
    cost: { gold: 200, hay: 15 },
    feedCost: { hay: 4, water: 2 },
    feedInterval: 25000,
    production: { wool: 5, gold: 24 },
    productionInterval: 22000,
    unlocked: false,
    requiredTech: 'tech_livestock',
    tier: 2,
    category: 'livestock',
  },
  {
    id: 'pig',
    name: 'Pig',
    icon: '🐷',
    description: 'Fast growing, produces meat',
    cost: { gold: 220, hay: 12 },
    feedCost: { hay: 6, water: 2 },
    feedInterval: 22000,
    production: { meat: 7, gold: 35 },
    productionInterval: 20000,
    unlocked: false,
    requiredTech: 'tech_livestock',
    tier: 2,
    category: 'livestock',
  },
  {
    id: 'goat',
    name: 'Goat',
    icon: '🐐',
    description: 'Produces milk and leather',
    cost: { gold: 170, hay: 10 },
    feedCost: { hay: 3, water: 2 },
    feedInterval: 20000,
    production: { milk: 4, leather: 1, gold: 22 },
    productionInterval: 18000,
    unlocked: false,
    requiredTech: 'tech_advanced_livestock',
    tier: 3,
    category: 'livestock',
  },
  {
    id: 'duck',
    name: 'Duck',
    icon: '🦆',
    description: 'Produces eggs and feathers',
    cost: { gold: 140, hay: 8 },
    feedCost: { hay: 2, water: 2 },
    feedInterval: 18000,
    production: { eggs: 5, gold: 18 },
    productionInterval: 14000,
    unlocked: false,
    requiredTech: 'tech_poultry_expansion',
    tier: 3,
    category: 'poultry',
  },
  {
    id: 'turkey',
    name: 'Turkey',
    icon: '🦃',
    description: 'Large poultry, produces quality meat',
    cost: { gold: 180, hay: 10 },
    feedCost: { hay: 4, water: 2 },
    feedInterval: 24000,
    production: { meat: 8, eggs: 3, gold: 32 },
    productionInterval: 22000,
    unlocked: false,
    requiredTech: 'tech_poultry_expansion',
    tier: 3,
    category: 'poultry',
  },
  {
    id: 'rabbit',
    name: 'Rabbit',
    icon: '🐰',
    description: 'Fast breeding, fur and meat',
    cost: { gold: 120, hay: 6 },
    feedCost: { hay: 2, water: 1 },
    feedInterval: 16000,
    production: { meat: 4, leather: 1, gold: 20 },
    productionInterval: 16000,
    unlocked: false,
    requiredTech: 'tech_small_animals',
    tier: 2,
    category: 'livestock',
  },
  {
    id: 'quail',
    name: 'Quail',
    icon: '🐦',
    description: 'Small gamebird, produces tiny eggs',
    cost: { gold: 90, hay: 5 },
    feedCost: { hay: 1, water: 1 },
    feedInterval: 14000,
    production: { eggs: 6, gold: 15 },
    productionInterval: 12000,
    unlocked: false,
    requiredTech: 'tech_small_animals',
    tier: 2,
    category: 'poultry',
  },
  {
    id: 'horse',
    name: 'Horse',
    icon: '🐴',
    description: 'Premium livestock, reduces work time',
    cost: { gold: 900, hay: 40, energy: 20 },
    feedCost: { hay: 8, water: 5 },
    feedInterval: 35000,
    production: { gold: 95, leather: 2 },
    productionInterval: 40000,
    unlocked: false,
    requiredTech: 'tech_premium_livestock',
    tier: 4,
    category: 'livestock',
  },
  {
    id: 'donkey',
    name: 'Donkey',
    icon: '🫏',
    description: 'Hardy work animal, steady income',
    cost: { gold: 450, hay: 25 },
    feedCost: { hay: 6, water: 3 },
    feedInterval: 28000,
    production: { gold: 55, leather: 1 },
    productionInterval: 32000,
    unlocked: false,
    requiredTech: 'tech_premium_livestock',
    tier: 3,
    category: 'livestock',
  },
  {
    id: 'alpaca',
    name: 'Alpaca',
    icon: '🦙',
    description: 'Premium fiber producer, friendly',
    cost: { gold: 650, hay: 30, energy: 10 },
    feedCost: { hay: 5, water: 3 },
    feedInterval: 26000,
    production: { wool: 9, gold: 70 },
    productionInterval: 30000,
    unlocked: false,
    requiredTech: 'tech_fiber_animals',
    tier: 4,
    category: 'livestock',
  },
  {
    id: 'llama',
    name: 'Llama',
    icon: '🦙',
    description: 'Exotic, produces premium wool',
    cost: { gold: 700, hay: 35, energy: 15 },
    feedCost: { hay: 6, water: 3 },
    feedInterval: 30000,
    production: { wool: 10, gold: 75 },
    productionInterval: 35000,
    unlocked: false,
    requiredTech: 'tech_exotic_animals',
    tier: 5,
    category: 'exotic',
  },
  {
    id: 'peacock',
    name: 'Peacock',
    icon: '🦚',
    description: 'Rare ornamental bird, high value',
    cost: { gold: 1400, hay: 25, energy: 25 },
    feedCost: { hay: 4, water: 3 },
    feedInterval: 28000,
    production: { gold: 140, research: 6 },
    productionInterval: 32000,
    unlocked: false,
    requiredTech: 'tech_exotic_animals',
    tier: 5,
    category: 'exotic',
  },
  {
    id: 'ostrich',
    name: 'Ostrich',
    icon: '🦤',
    description: 'Giant bird, large eggs and leather',
    cost: { gold: 1100, hay: 35, energy: 20 },
    feedCost: { hay: 7, water: 4 },
    feedInterval: 32000,
    production: { eggs: 8, leather: 3, gold: 100 },
    productionInterval: 38000,
    unlocked: false,
    requiredTech: 'tech_exotic_animals',
    tier: 5,
    category: 'exotic',
  },
  {
    id: 'deer',
    name: 'Deer',
    icon: '🦌',
    description: 'Gentle wildlife, premium venison',
    cost: { gold: 800, hay: 30, energy: 18 },
    feedCost: { hay: 5, water: 3 },
    feedInterval: 30000,
    production: { meat: 12, leather: 2, gold: 85 },
    productionInterval: 36000,
    unlocked: false,
    requiredTech: 'tech_game_animals',
    tier: 4,
    category: 'exotic',
  },
  {
    id: 'bison',
    name: 'Bison',
    icon: '🦬',
    description: 'Massive beast, premium meat and hide',
    cost: { gold: 1500, hay: 50, energy: 30 },
    feedCost: { hay: 10, water: 6 },
    feedInterval: 40000,
    production: { meat: 20, leather: 5, gold: 150 },
    productionInterval: 50000,
    unlocked: false,
    requiredTech: 'tech_large_game',
    tier: 6,
    category: 'exotic',
  },
  {
    id: 'bee_hive',
    name: 'Bee Hive',
    icon: '🐝',
    description: 'Produces honey and boosts crops',
    cost: { gold: 350, energy: 10 },
    feedCost: { water: 1 },
    feedInterval: 18000,
    production: { gold: 45, research: 2 },
    productionInterval: 20000,
    unlocked: false,
    requiredTech: 'tech_apiculture',
    tier: 3,
    category: 'livestock',
  },
  {
    id: 'fish_pond',
    name: 'Fish Pond',
    icon: '🐟',
    description: 'Aquaculture system, produces fish',
    cost: { gold: 500, water: 30, energy: 15 },
    feedCost: { water: 3 },
    feedInterval: 25000,
    production: { meat: 10, gold: 60 },
    productionInterval: 28000,
    unlocked: false,
    requiredTech: 'tech_aquaculture',
    tier: 4,
    category: 'livestock',
  },
  {
    id: 'swan',
    name: 'Swan',
    icon: '🦢',
    description: 'Elegant waterfowl, ornamental value',
    cost: { gold: 900, hay: 20, energy: 20 },
    feedCost: { hay: 3, water: 4 },
    feedInterval: 26000,
    production: { gold: 110, research: 4 },
    productionInterval: 30000,
    unlocked: false,
    requiredTech: 'tech_exotic_animals',
    tier: 5,
    category: 'exotic',
  },
]

export const BUILDINGS: Building[] = [
  {
    id: 'well',
    name: 'Well',
    icon: '🪣',
    description: 'Produces water continuously',
    cost: { gold: 60 },
    buildTime: 0,
    production: { water: 5 },
    productionRate: 8000,
    unlocked: true,
    tier: 1,
    category: 'production',
  },
  {
    id: 'windmill',
    name: 'Windmill',
    icon: '🌬️',
    description: 'Generates renewable energy',
    cost: { gold: 140, water: 10 },
    buildTime: 0,
    production: { energy: 10 },
    productionRate: 12000,
    unlocked: false,
    requiredTech: 'tech_windmill',
    tier: 2,
    category: 'production',
  },
  {
    id: 'compost',
    name: 'Compost Heap',
    icon: '♻️',
    description: 'Recycles waste into fertilizer',
    cost: { gold: 100, water: 5 },
    buildTime: 0,
    production: { fertilizer: 3 },
    productionRate: 10000,
    unlocked: false,
    requiredTech: 'tech_composting',
    tier: 2,
    category: 'processing',
  },
  {
    id: 'seed_maker',
    name: 'Seed Maker',
    icon: '🌱',
    description: 'Automatically produces seeds',
    cost: { gold: 180, energy: 15 },
    buildTime: 0,
    production: { seeds: 5 },
    productionRate: 13000,
    unlocked: false,
    requiredTech: 'tech_seed_production',
    tier: 3,
    category: 'production',
  },
  {
    id: 'greenhouse',
    name: 'Greenhouse',
    icon: '🏡',
    description: 'Boosts nearby crop growth',
    cost: { gold: 300, energy: 25, water: 20 },
    buildTime: 0,
    production: { research: 0.5 },
    productionRate: 20000,
    unlocked: false,
    requiredTech: 'tech_greenhouse',
    tier: 3,
    category: 'utility',
  },
  {
    id: 'research_lab',
    name: 'Research Lab',
    icon: '🔬',
    description: 'Generates research points for tech',
    cost: { gold: 350, energy: 20 },
    buildTime: 0,
    production: { research: 1.5 },
    productionRate: 15000,
    unlocked: true,
    tier: 1,
    category: 'production',
  },
  {
    id: 'barn',
    name: 'Barn',
    icon: '🏚️',
    description: 'Stores hay and animal feed',
    cost: { gold: 350, water: 30 },
    buildTime: 0,
    production: { hay: 7 },
    productionRate: 15000,
    unlocked: false,
    requiredTech: 'tech_barn',
    tier: 3,
    category: 'production',
  },
  {
    id: 'water_tower',
    name: 'Water Tower',
    icon: '💧',
    description: 'Advanced water storage and distribution',
    cost: { gold: 250, water: 40 },
    buildTime: 0,
    production: { water: 12 },
    productionRate: 10000,
    unlocked: false,
    requiredTech: 'tech_irrigation',
    tier: 3,
    category: 'production',
  },
  {
    id: 'fertilizer_plant',
    name: 'Fertilizer Plant',
    icon: '🧪',
    description: 'Chemical fertilizer production',
    cost: { gold: 450, energy: 30 },
    buildTime: 0,
    production: { fertilizer: 8 },
    productionRate: 14000,
    unlocked: false,
    requiredTech: 'tech_chemical_farming',
    tier: 4,
    category: 'production',
  },
  {
    id: 'dairy',
    name: 'Dairy',
    icon: '🥛',
    description: 'Processes milk into premium goods',
    cost: { gold: 550, energy: 35 },
    buildTime: 0,
    production: { gold: 50 },
    productionRate: 20000,
    unlocked: false,
    requiredTech: 'tech_processing',
    tier: 4,
    category: 'processing',
  },
  {
    id: 'bakery',
    name: 'Bakery',
    icon: '🍞',
    description: 'Converts grain into baked goods',
    cost: { gold: 650, energy: 40 },
    buildTime: 0,
    production: { gold: 60 },
    productionRate: 22000,
    unlocked: false,
    requiredTech: 'tech_processing',
    tier: 4,
    category: 'processing',
  },
  {
    id: 'butcher',
    name: 'Butcher Shop',
    icon: '🥩',
    description: 'Processes meat into premium cuts',
    cost: { gold: 600, energy: 38 },
    buildTime: 0,
    production: { gold: 55 },
    productionRate: 21000,
    unlocked: false,
    requiredTech: 'tech_processing',
    tier: 4,
    category: 'processing',
  },
  {
    id: 'textile_mill',
    name: 'Textile Mill',
    icon: '🧵',
    description: 'Processes wool into fabric',
    cost: { gold: 700, energy: 45 },
    buildTime: 0,
    production: { gold: 70 },
    productionRate: 23000,
    unlocked: false,
    requiredTech: 'tech_textile_production',
    tier: 4,
    category: 'processing',
  },
  {
    id: 'silo',
    name: 'Storage Silo',
    icon: '🏢',
    description: 'Increases resource storage capacity',
    cost: { gold: 400, water: 20 },
    buildTime: 0,
    production: { gold: 20 },
    productionRate: 30000,
    capacity: 1000,
    unlocked: false,
    requiredTech: 'tech_storage',
    tier: 3,
    category: 'utility',
  },
  {
    id: 'warehouse',
    name: 'Warehouse',
    icon: '🏭',
    description: 'Massive storage for all resources',
    cost: { gold: 800, energy: 20 },
    buildTime: 0,
    production: { gold: 35 },
    productionRate: 28000,
    capacity: 2500,
    unlocked: false,
    requiredTech: 'tech_logistics',
    tier: 5,
    category: 'utility',
  },
  {
    id: 'market',
    name: 'Farmers Market',
    icon: '🏪',
    description: 'Sells goods for premium prices',
    cost: { gold: 900, energy: 25 },
    buildTime: 0,
    production: { gold: 85, research: 2 },
    productionRate: 24000,
    unlocked: false,
    requiredTech: 'tech_commerce',
    tier: 5,
    category: 'processing',
  },
  {
    id: 'solar_panel',
    name: 'Solar Panel',
    icon: '☀️',
    description: 'Advanced energy generation',
    cost: { gold: 900, energy: 50, research: 10 },
    buildTime: 0,
    production: { energy: 25 },
    productionRate: 10000,
    unlocked: false,
    requiredTech: 'tech_solar',
    tier: 5,
    category: 'production',
  },
  {
    id: 'hydro_generator',
    name: 'Hydro Generator',
    icon: '⚡',
    description: 'Water-powered energy production',
    cost: { gold: 1000, water: 50, research: 12 },
    buildTime: 0,
    production: { energy: 30 },
    productionRate: 9000,
    unlocked: false,
    requiredTech: 'tech_hydropower',
    tier: 5,
    category: 'production',
  },
  {
    id: 'bio_reactor',
    name: 'Bio Reactor',
    icon: '🔋',
    description: 'Converts biomass to energy',
    cost: { gold: 1200, energy: 60, research: 15 },
    buildTime: 0,
    production: { energy: 40, research: 1 },
    productionRate: 12000,
    unlocked: false,
    requiredTech: 'tech_bioenergy',
    tier: 6,
    category: 'production',
  },
  {
    id: 'auto_harvester',
    name: 'Auto Harvester',
    icon: '🤖',
    description: 'Automatically harvests crops',
    cost: { gold: 1400, energy: 80, research: 18 },
    buildTime: 0,
    production: { research: 2 },
    productionRate: 20000,
    unlocked: false,
    requiredTech: 'tech_automation',
    tier: 5,
    category: 'automation',
  },
  {
    id: 'auto_planter',
    name: 'Auto Planter',
    icon: '🚜',
    description: 'Automates planting operations',
    cost: { gold: 1600, energy: 90, research: 20 },
    buildTime: 0,
    production: { research: 2.5 },
    productionRate: 20000,
    unlocked: false,
    requiredTech: 'tech_automation',
    tier: 5,
    category: 'automation',
  },
  {
    id: 'auto_feeder',
    name: 'Auto Feeder',
    icon: '🤖',
    description: 'Automatically feeds animals',
    cost: { gold: 1300, energy: 70, research: 16 },
    buildTime: 0,
    production: { research: 1.5 },
    productionRate: 20000,
    unlocked: false,
    requiredTech: 'tech_animal_automation',
    tier: 5,
    category: 'automation',
  },
  {
    id: 'weather_station',
    name: 'Weather Station',
    icon: '🌦️',
    description: 'Predicts weather, optimizes farming',
    cost: { gold: 800, energy: 40, research: 20 },
    buildTime: 0,
    production: { research: 3 },
    productionRate: 18000,
    unlocked: false,
    requiredTech: 'tech_meteorology',
    tier: 5,
    category: 'utility',
  },
  {
    id: 'gene_lab',
    name: 'Genetics Lab',
    icon: '🧬',
    description: 'Research crop and animal improvements',
    cost: { gold: 2000, energy: 100, research: 30 },
    buildTime: 0,
    production: { research: 8 },
    productionRate: 16000,
    unlocked: false,
    requiredTech: 'tech_genetics',
    tier: 6,
    category: 'production',
  },
  {
    id: 'factory',
    name: 'Processing Factory',
    icon: '🏭',
    description: 'Mass produces advanced goods',
    cost: { gold: 2500, energy: 120, research: 35 },
    buildTime: 0,
    production: { gold: 150, research: 5 },
    productionRate: 25000,
    unlocked: false,
    requiredTech: 'tech_industrialization',
    tier: 6,
    category: 'processing',
  },
  {
    id: 'export_terminal',
    name: 'Export Terminal',
    icon: '🚢',
    description: 'Ships goods internationally for premium',
    cost: { gold: 3000, energy: 150, research: 40 },
    buildTime: 0,
    production: { gold: 200, research: 6 },
    productionRate: 28000,
    unlocked: false,
    requiredTech: 'tech_global_trade',
    tier: 6,
    category: 'processing',
  },
  {
    id: 'quantum_farm',
    name: 'Quantum Farm',
    icon: '✨',
    description: 'Experimental technology, massive yields',
    cost: { gold: 5000, energy: 200, research: 60 },
    buildTime: 0,
    production: { gold: 300, research: 10, energy: 20 },
    productionRate: 30000,
    unlocked: false,
    requiredTech: 'tech_quantum_agriculture',
    tier: 6,
    category: 'automation',
  },
]

export const TECH_TREE: Tech[] = [
  { id: 'tech_root_crops', name: 'Root Vegetables', description: 'Unlock carrots, potatoes, onions', cost: 5, category: 'crops', unlocked: true, purchased: false, prerequisites: [], effect: 'unlock_crops', tier: 1 },
  { id: 'tech_tomatoes', name: 'Tomato Cultivation', description: 'Unlock tomatoes and peppers', cost: 5, category: 'crops', unlocked: true, purchased: false, prerequisites: [], effect: 'unlock_crop_tomato', tier: 1 },
  { id: 'tech_leafy_greens', name: 'Leafy Greens', description: 'Unlock lettuce and cabbage', cost: 6, category: 'crops', unlocked: true, purchased: false, prerequisites: [], effect: 'unlock_greens', tier: 1 },
  { id: 'tech_berries', name: 'Berry Farming', description: 'Unlock strawberries and blueberries', cost: 10, category: 'crops', unlocked: true, purchased: false, prerequisites: [], effect: 'unlock_crop_strawberry', tier: 2 },
  { id: 'tech_fruit_crops', name: 'Fruit Orchards', description: 'Unlock apples, grapes, peaches, cherries', cost: 12, category: 'crops', unlocked: false, purchased: false, prerequisites: ['tech_berries'], effect: 'unlock_crop_grapes', tier: 2 },
  { id: 'tech_specialty_crops', name: 'Specialty Crops', description: 'Unlock pumpkins, watermelons, eggplant', cost: 15, category: 'crops', unlocked: false, purchased: false, prerequisites: ['tech_tomatoes', 'tech_root_crops'], effect: 'unlock_specialty', tier: 2 },
  { id: 'tech_advanced_grains', name: 'Advanced Grains', description: 'Unlock rice, barley, oats, quinoa', cost: 20, category: 'crops', unlocked: false, purchased: false, prerequisites: ['tech_specialty_crops'], effect: 'unlock_crop_rice', tier: 3 },
  { id: 'tech_oil_crops', name: 'Oil Seed Crops', description: 'Unlock sunflowers and soybeans', cost: 22, category: 'crops', unlocked: false, purchased: false, prerequisites: ['tech_advanced_grains'], effect: 'unlock_oil_crops', tier: 3 },
  { id: 'tech_industrial_crops', name: 'Industrial Crops', description: 'Unlock hemp and cotton for materials', cost: 28, category: 'crops', unlocked: false, purchased: false, prerequisites: ['tech_oil_crops'], effect: 'unlock_industrial_crops', tier: 4 },
  { id: 'tech_mushroom_cultivation', name: 'Mushroom Cultivation', description: 'Unlock gourmet mushrooms', cost: 26, category: 'crops', unlocked: false, purchased: false, prerequisites: ['tech_specialty_crops'], effect: 'unlock_mushroom', tier: 4 },
  { id: 'tech_exotic_fruits', name: 'Tropical Fruits', description: 'Unlock mango, pineapple, dragon fruit, avocado', cost: 35, category: 'crops', unlocked: false, purchased: false, prerequisites: ['tech_fruit_crops'], effect: 'unlock_exotic_fruits', tier: 4 },
  { id: 'tech_export_crops', name: 'Export Crops', description: 'Unlock coffee and cocoa for export', cost: 40, category: 'crops', unlocked: false, purchased: false, prerequisites: ['tech_exotic_fruits', 'tech_industrial_crops'], effect: 'unlock_export', tier: 5 },
  { id: 'tech_spice_crops', name: 'Spice Cultivation', description: 'Unlock vanilla and saffron', cost: 50, category: 'exotic', unlocked: false, purchased: false, prerequisites: ['tech_export_crops'], effect: 'unlock_spices', tier: 5 },
  { id: 'tech_luxury_crops', name: 'Luxury Agriculture', description: 'Unlock truffles and rare crops', cost: 65, category: 'exotic', unlocked: false, purchased: false, prerequisites: ['tech_spice_crops', 'tech_mushroom_cultivation'], effect: 'unlock_luxury_crops', tier: 6 },
  { id: 'tech_bioengineering', name: 'Bioengineering', description: 'Unlock crystal grain and golden wheat', cost: 80, category: 'exotic', unlocked: false, purchased: false, prerequisites: ['tech_luxury_crops'], effect: 'unlock_crystal', tier: 6 },
  
  { id: 'tech_livestock', name: 'Animal Husbandry', description: 'Unlock cows, sheep, pigs', cost: 8, category: 'animals', unlocked: true, purchased: false, prerequisites: [], effect: 'unlock_basic_animals', tier: 1 },
  { id: 'tech_small_animals', name: 'Small Animals', description: 'Unlock rabbits and quail', cost: 10, category: 'animals', unlocked: false, purchased: false, prerequisites: [], effect: 'unlock_small_animals', tier: 1 },
  { id: 'tech_advanced_livestock', name: 'Advanced Livestock', description: 'Unlock goats and donkeys', cost: 15, category: 'animals', unlocked: false, purchased: false, prerequisites: ['tech_livestock'], effect: 'unlock_goat', tier: 2 },
  { id: 'tech_poultry_expansion', name: 'Poultry Expansion', description: 'Unlock ducks and turkeys', cost: 12, category: 'animals', unlocked: false, purchased: false, prerequisites: ['tech_livestock'], effect: 'unlock_duck', tier: 2 },
  { id: 'tech_fiber_animals', name: 'Fiber Animals', description: 'Unlock alpacas for premium fiber', cost: 22, category: 'animals', unlocked: false, purchased: false, prerequisites: ['tech_advanced_livestock'], effect: 'unlock_alpaca', tier: 3 },
  { id: 'tech_premium_livestock', name: 'Premium Livestock', description: 'Unlock horses for work', cost: 28, category: 'animals', unlocked: false, purchased: false, prerequisites: ['tech_fiber_animals'], effect: 'unlock_horse', tier: 3 },
  { id: 'tech_apiculture', name: 'Beekeeping', description: 'Unlock bee hives for honey', cost: 20, category: 'animals', unlocked: false, purchased: false, prerequisites: ['tech_poultry_expansion'], effect: 'unlock_bees', tier: 3 },
  { id: 'tech_aquaculture', name: 'Aquaculture', description: 'Unlock fish ponds', cost: 30, category: 'animals', unlocked: false, purchased: false, prerequisites: ['tech_apiculture'], effect: 'unlock_fish', tier: 4 },
  { id: 'tech_game_animals', name: 'Game Animals', description: 'Unlock deer for premium meat', cost: 38, category: 'animals', unlocked: false, purchased: false, prerequisites: ['tech_premium_livestock'], effect: 'unlock_deer', tier: 4 },
  { id: 'tech_exotic_animals', name: 'Exotic Animals', description: 'Unlock llamas, peacocks, ostriches, swans', cost: 45, category: 'exotic', unlocked: false, purchased: false, prerequisites: ['tech_game_animals', 'tech_aquaculture'], effect: 'unlock_exotic_animals', tier: 5 },
  { id: 'tech_large_game', name: 'Large Game', description: 'Unlock bison for massive yields', cost: 70, category: 'exotic', unlocked: false, purchased: false, prerequisites: ['tech_exotic_animals'], effect: 'unlock_bison', tier: 6 },
  
  { id: 'tech_windmill', name: 'Wind Power', description: 'Unlock windmill for energy', cost: 6, category: 'buildings', unlocked: true, purchased: false, prerequisites: [], effect: 'unlock_building_windmill', tier: 1 },
  { id: 'tech_composting', name: 'Composting', description: 'Unlock compost heap for fertilizer', cost: 6, category: 'buildings', unlocked: true, purchased: false, prerequisites: [], effect: 'unlock_building_compost', tier: 1 },
  { id: 'tech_seed_production', name: 'Seed Production', description: 'Automate seed generation', cost: 10, category: 'buildings', unlocked: false, purchased: false, prerequisites: ['tech_composting'], effect: 'unlock_building_seed_maker', tier: 2 },
  { id: 'tech_greenhouse', name: 'Greenhouse Technology', description: 'Build greenhouses to boost growth', cost: 18, category: 'buildings', unlocked: false, purchased: false, prerequisites: ['tech_windmill'], effect: 'unlock_building_greenhouse', tier: 2 },
  { id: 'tech_barn', name: 'Barn Construction', description: 'Build barns for hay storage', cost: 15, category: 'buildings', unlocked: false, purchased: false, prerequisites: ['tech_livestock'], effect: 'unlock_building_barn', tier: 2 },
  { id: 'tech_irrigation', name: 'Irrigation Systems', description: 'Unlock water towers', cost: 16, category: 'buildings', unlocked: false, purchased: false, prerequisites: ['tech_seed_production'], effect: 'unlock_water_tower', tier: 2 },
  { id: 'tech_storage', name: 'Advanced Storage', description: 'Build silos for bulk storage', cost: 22, category: 'buildings', unlocked: false, purchased: false, prerequisites: ['tech_barn', 'tech_irrigation'], effect: 'unlock_building_storage_silo', tier: 3 },
  { id: 'tech_chemical_farming', name: 'Chemical Farming', description: 'Unlock fertilizer plant', cost: 26, category: 'buildings', unlocked: false, purchased: false, prerequisites: ['tech_storage'], effect: 'unlock_fertilizer_plant', tier: 3 },
  { id: 'tech_processing', name: 'Food Processing', description: 'Unlock dairy, bakery, butcher', cost: 30, category: 'processing', unlocked: false, purchased: false, prerequisites: ['tech_barn', 'tech_advanced_grains'], effect: 'unlock_processing_buildings', tier: 3 },
  { id: 'tech_textile_production', name: 'Textile Production', description: 'Unlock textile mill', cost: 32, category: 'processing', unlocked: false, purchased: false, prerequisites: ['tech_processing', 'tech_fiber_animals'], effect: 'unlock_textile_mill', tier: 4 },
  { id: 'tech_logistics', name: 'Logistics', description: 'Unlock warehouses for massive storage', cost: 35, category: 'buildings', unlocked: false, purchased: false, prerequisites: ['tech_storage'], effect: 'unlock_warehouse', tier: 4 },
  { id: 'tech_commerce', name: 'Commerce', description: 'Unlock farmers market for premium sales', cost: 38, category: 'processing', unlocked: false, purchased: false, prerequisites: ['tech_textile_production'], effect: 'unlock_market', tier: 5 },
  { id: 'tech_solar', name: 'Solar Energy', description: 'Unlock solar panels', cost: 40, category: 'buildings', unlocked: false, purchased: false, prerequisites: ['tech_greenhouse'], effect: 'unlock_building_solar_panel', tier: 4 },
  { id: 'tech_hydropower', name: 'Hydroelectric Power', description: 'Unlock hydro generators', cost: 45, category: 'buildings', unlocked: false, purchased: false, prerequisites: ['tech_solar', 'tech_irrigation'], effect: 'unlock_hydro_generator', tier: 5 },
  { id: 'tech_bioenergy', name: 'Bioenergy', description: 'Unlock bio reactors', cost: 55, category: 'buildings', unlocked: false, purchased: false, prerequisites: ['tech_hydropower'], effect: 'unlock_bio_reactor', tier: 6 },
  { id: 'tech_meteorology', name: 'Meteorology', description: 'Unlock weather station', cost: 42, category: 'buildings', unlocked: false, purchased: false, prerequisites: ['tech_solar'], effect: 'unlock_weather_station', tier: 5 },
  { id: 'tech_automation', name: 'Farm Automation', description: 'Unlock auto harvester and planter', cost: 50, category: 'automation', unlocked: false, purchased: false, prerequisites: ['tech_solar'], effect: 'unlock_building_auto_harvester', tier: 5 },
  { id: 'tech_animal_automation', name: 'Animal Automation', description: 'Unlock auto feeder', cost: 48, category: 'automation', unlocked: false, purchased: false, prerequisites: ['tech_automation'], effect: 'unlock_auto_feeder', tier: 5 },
  { id: 'tech_genetics', name: 'Genetics Research', description: 'Unlock genetics lab', cost: 65, category: 'buildings', unlocked: false, purchased: false, prerequisites: ['tech_meteorology'], effect: 'unlock_gene_lab', tier: 6 },
  { id: 'tech_industrialization', name: 'Industrialization', description: 'Unlock processing factory', cost: 75, category: 'buildings', unlocked: false, purchased: false, prerequisites: ['tech_automation', 'tech_commerce'], effect: 'unlock_building_factory', tier: 6 },
  { id: 'tech_global_trade', name: 'Global Trade', description: 'Unlock export terminal', cost: 85, category: 'processing', unlocked: false, purchased: false, prerequisites: ['tech_industrialization'], effect: 'unlock_export_terminal', tier: 6 },
  { id: 'tech_quantum_agriculture', name: 'Quantum Agriculture', description: 'Unlock quantum farm', cost: 120, category: 'automation', unlocked: false, purchased: false, prerequisites: ['tech_genetics', 'tech_global_trade', 'tech_bioenergy'], effect: 'unlock_quantum_farm', tier: 6 },
  
  { id: 'tech_faster_growth', name: 'Enhanced Growth', description: 'Crops grow 15% faster', cost: 8, category: 'efficiency', unlocked: true, purchased: false, prerequisites: [], effect: 'growth_speed_1.15', tier: 1 },
  { id: 'tech_better_yield', name: 'Improved Yields', description: 'Harvest yields +25%', cost: 12, category: 'efficiency', unlocked: false, purchased: false, prerequisites: ['tech_faster_growth'], effect: 'yield_multiplier_1.25', tier: 2 },
  { id: 'tech_rapid_growth', name: 'Rapid Growth', description: 'Crops grow 20% faster', cost: 18, category: 'efficiency', unlocked: false, purchased: false, prerequisites: ['tech_better_yield'], effect: 'growth_speed_1.20', tier: 3 },
  { id: 'tech_superior_yields', name: 'Superior Yields', description: 'Harvest yields +35%', cost: 28, category: 'efficiency', unlocked: false, purchased: false, prerequisites: ['tech_rapid_growth'], effect: 'yield_multiplier_1.35', tier: 4 },
  { id: 'tech_water_efficiency', name: 'Water Conservation', description: 'Water costs -30%', cost: 10, category: 'efficiency', unlocked: true, purchased: false, prerequisites: [], effect: 'water_cost_0.70', tier: 1 },
  { id: 'tech_advanced_irrigation', name: 'Advanced Irrigation', description: 'Water costs -40%', cost: 16, category: 'efficiency', unlocked: false, purchased: false, prerequisites: ['tech_water_efficiency', 'tech_irrigation'], effect: 'water_cost_0.60', tier: 3 },
  { id: 'tech_energy_efficiency', name: 'Energy Efficiency', description: 'Energy production +50%', cost: 18, category: 'efficiency', unlocked: false, purchased: false, prerequisites: ['tech_water_efficiency', 'tech_windmill'], effect: 'energy_production_1.5', tier: 2 },
  { id: 'tech_power_optimization', name: 'Power Optimization', description: 'Energy production +75%', cost: 30, category: 'efficiency', unlocked: false, purchased: false, prerequisites: ['tech_energy_efficiency', 'tech_solar'], effect: 'energy_production_1.75', tier: 4 },
  { id: 'tech_fertilizer_mastery', name: 'Fertilizer Mastery', description: 'Fertilizer efficiency +40%', cost: 15, category: 'efficiency', unlocked: false, purchased: false, prerequisites: ['tech_composting'], effect: 'fertilizer_efficiency_1.4', tier: 2 },
  { id: 'tech_soil_science', name: 'Soil Science', description: 'Fertilizer efficiency +60%', cost: 24, category: 'efficiency', unlocked: false, purchased: false, prerequisites: ['tech_fertilizer_mastery'], effect: 'fertilizer_efficiency_1.6', tier: 3 },
  { id: 'tech_animal_care', name: 'Animal Care', description: 'Animal production +30%', cost: 20, category: 'efficiency', unlocked: false, purchased: false, prerequisites: ['tech_livestock'], effect: 'animal_production_1.3', tier: 2 },
  { id: 'tech_veterinary_science', name: 'Veterinary Science', description: 'Animal production +50%', cost: 32, category: 'efficiency', unlocked: false, purchased: false, prerequisites: ['tech_animal_care', 'tech_advanced_livestock'], effect: 'animal_production_1.5', tier: 4 },
  { id: 'tech_breeding_program', name: 'Breeding Program', description: 'Animal yields +50%', cost: 35, category: 'efficiency', unlocked: false, purchased: false, prerequisites: ['tech_animal_care'], effect: 'animal_yield_1.5', tier: 3 },
  { id: 'tech_genetic_selection', name: 'Genetic Selection', description: 'Animal yields +80%', cost: 55, category: 'efficiency', unlocked: false, purchased: false, prerequisites: ['tech_breeding_program', 'tech_genetics'], effect: 'animal_yield_1.8', tier: 5 },
  { id: 'tech_crop_rotation', name: 'Crop Rotation', description: 'All crop yields +20%', cost: 25, category: 'efficiency', unlocked: false, purchased: false, prerequisites: ['tech_better_yield'], effect: 'crop_rotation_1.2', tier: 3 },
  { id: 'tech_permaculture', name: 'Permaculture', description: 'All crop yields +35%', cost: 45, category: 'efficiency', unlocked: false, purchased: false, prerequisites: ['tech_crop_rotation'], effect: 'crop_rotation_1.35', tier: 5 },
  { id: 'tech_lucky_harvest', name: 'Lucky Harvest', description: 'Critical harvest chance +2%', cost: 15, category: 'efficiency', unlocked: false, purchased: false, prerequisites: ['tech_better_yield'], effect: 'luck_level_1', tier: 2 },
  { id: 'tech_fortune_farming', name: 'Fortune Farming', description: 'Critical chance and yields improve', cost: 30, category: 'efficiency', unlocked: false, purchased: false, prerequisites: ['tech_lucky_harvest'], effect: 'luck_level_1', tier: 3 },
  { id: 'tech_golden_touch', name: 'Golden Touch', description: 'Critical harvests more common', cost: 50, category: 'efficiency', unlocked: false, purchased: false, prerequisites: ['tech_fortune_farming'], effect: 'luck_level_1', tier: 4 },
  { id: 'tech_divine_blessing', name: 'Divine Blessing', description: 'Master luck - criticals everywhere', cost: 80, category: 'efficiency', unlocked: false, purchased: false, prerequisites: ['tech_golden_touch'], effect: 'luck_level_2', tier: 5 },
  { id: 'tech_master_farmer', name: 'Master Farmer', description: 'All bonuses +25%', cost: 100, category: 'efficiency', unlocked: false, purchased: false, prerequisites: ['tech_superior_yields', 'tech_breeding_program', 'tech_automation'], effect: 'master_multiplier_1.25', tier: 5 },
  { id: 'tech_legendary_farmer', name: 'Legendary Farmer', description: 'All bonuses +50%', cost: 150, category: 'efficiency', unlocked: false, purchased: false, prerequisites: ['tech_master_farmer', 'tech_permaculture', 'tech_genetic_selection'], effect: 'master_multiplier_1.5', tier: 6 },
]

export const ACHIEVEMENTS: Achievement[] = [
  { id: 'first_harvest', name: 'First Harvest', description: 'Harvest your first crop', category: 'harvest', requirement: 1, progress: 0, completed: false, reward: { gold: 50, seeds: 5 }, tier: 1 },
  { id: 'harvest_10', name: 'Growing Farm', description: 'Harvest 10 crops', category: 'harvest', requirement: 10, progress: 0, completed: false, reward: { research: 2, gold: 50 }, tier: 1 },
  { id: 'harvest_50', name: 'Productive Farm', description: 'Harvest 50 crops', category: 'harvest', requirement: 50, progress: 0, completed: false, reward: { research: 5, gold: 150 }, tier: 2 },
  { id: 'harvest_100', name: 'Abundant Harvest', description: 'Harvest 100 crops', category: 'harvest', requirement: 100, progress: 0, completed: false, reward: { gold: 400, research: 10 }, tier: 2 },
  { id: 'harvest_250', name: 'Prolific Harvester', description: 'Harvest 250 crops', category: 'harvest', requirement: 250, progress: 0, completed: false, reward: { gold: 800, research: 12 }, tier: 3 },
  { id: 'harvest_500', name: 'Master Harvester', description: 'Harvest 500 crops', category: 'harvest', requirement: 500, progress: 0, completed: false, reward: { gold: 1500, research: 18 }, tier: 3 },
  { id: 'harvest_1000', name: 'Harvest Legend', description: 'Harvest 1000 crops', category: 'harvest', requirement: 1000, progress: 0, completed: false, reward: { gold: 3500, research: 30 }, tier: 4 },
  { id: 'harvest_2500', name: 'Harvest Titan', description: 'Harvest 2500 crops', category: 'harvest', requirement: 2500, progress: 0, completed: false, reward: { gold: 8000, research: 50 }, tier: 5 },
  
  { id: 'wealth_500', name: 'First Fortune', description: 'Earn 500 gold', category: 'wealth', requirement: 500, progress: 0, completed: false, reward: { research: 2, seeds: 10 }, tier: 1 },
  { id: 'wealth_2000', name: 'Getting Rich', description: 'Earn 2,000 gold', category: 'wealth', requirement: 2000, progress: 0, completed: false, reward: { research: 5, gold: 150 }, tier: 2 },
  { id: 'wealth_10000', name: 'Wealthy Farmer', description: 'Earn 10,000 gold', category: 'wealth', requirement: 10000, progress: 0, completed: false, reward: { gold: 1200, research: 15 }, tier: 3 },
  { id: 'wealth_50000', name: 'Farm Tycoon', description: 'Earn 50,000 gold', category: 'wealth', requirement: 50000, progress: 0, completed: false, reward: { gold: 4000, research: 25 }, tier: 4 },
  { id: 'wealth_100000', name: 'Agricultural Mogul', description: 'Earn 100,000 gold', category: 'wealth', requirement: 100000, progress: 0, completed: false, reward: { gold: 12000, research: 45 }, tier: 5 },
  { id: 'wealth_250000', name: 'Empire Magnate', description: 'Earn 250,000 gold', category: 'wealth', requirement: 250000, progress: 0, completed: false, reward: { gold: 25000, research: 75 }, tier: 6 },
  
  { id: 'tech_first', name: 'Researcher', description: 'Unlock your first technology', category: 'tech', requirement: 1, progress: 0, completed: false, reward: { research: 3 }, tier: 1 },
  { id: 'tech_5', name: 'Tech Enthusiast', description: 'Unlock 5 technologies', category: 'tech', requirement: 5, progress: 0, completed: false, reward: { gold: 250, research: 6 }, tier: 2 },
  { id: 'tech_10', name: 'Tech Adopter', description: 'Unlock 10 technologies', category: 'tech', requirement: 10, progress: 0, completed: false, reward: { gold: 500, research: 10 }, tier: 2 },
  { id: 'tech_20', name: 'Tech Innovator', description: 'Unlock 20 technologies', category: 'tech', requirement: 20, progress: 0, completed: false, reward: { gold: 1000, research: 18 }, tier: 3 },
  { id: 'tech_35', name: 'Tech Pioneer', description: 'Unlock 35 technologies', category: 'tech', requirement: 35, progress: 0, completed: false, reward: { gold: 2000, research: 30 }, tier: 4 },
  { id: 'tech_50', name: 'Tech Master', description: 'Unlock 50 technologies', category: 'tech', requirement: 50, progress: 0, completed: false, reward: { gold: 4000, research: 50 }, tier: 5 },
  { id: 'tech_70', name: 'Tech God', description: 'Unlock 70 technologies', category: 'tech', requirement: 70, progress: 0, completed: false, reward: { gold: 8000, research: 80 }, tier: 6 },
  
  { id: 'first_animal', name: 'Rancher Begin', description: 'Purchase your first animal', category: 'animals', requirement: 1, progress: 0, completed: false, reward: { gold: 120, hay: 15 }, tier: 1 },
  { id: 'animals_3', name: 'Growing Ranch', description: 'Own 3 animals', category: 'animals', requirement: 3, progress: 0, completed: false, reward: { gold: 200, research: 3 }, tier: 1 },
  { id: 'animals_5', name: 'Diverse Ranch', description: 'Own 5 animals', category: 'animals', requirement: 5, progress: 0, completed: false, reward: { gold: 400, research: 6 }, tier: 2 },
  { id: 'animals_10', name: 'Ranch Master', description: 'Own 10 animals', category: 'animals', requirement: 10, progress: 0, completed: false, reward: { gold: 800, research: 12 }, tier: 3 },
  { id: 'animals_15', name: 'Master Rancher', description: 'Own 15 animals', category: 'animals', requirement: 15, progress: 0, completed: false, reward: { gold: 1500, research: 20 }, tier: 4 },
  { id: 'animals_20', name: 'Ranch Tycoon', description: 'Own 20 animals', category: 'animals', requirement: 20, progress: 0, completed: false, reward: { gold: 3000, research: 35 }, tier: 5 },
  
  { id: 'animal_products_20', name: 'Producer', description: 'Collect 20 animal products', category: 'production', requirement: 20, progress: 0, completed: false, reward: { gold: 150, research: 2 }, tier: 1 },
  { id: 'animal_products_50', name: 'Animal Products', description: 'Collect 50 animal products', category: 'production', requirement: 50, progress: 0, completed: false, reward: { gold: 300, research: 5 }, tier: 2 },
  { id: 'animal_products_150', name: 'Production Pro', description: 'Collect 150 animal products', category: 'production', requirement: 150, progress: 0, completed: false, reward: { gold: 700, research: 10 }, tier: 3 },
  { id: 'animal_products_300', name: 'Production Master', description: 'Collect 300 animal products', category: 'production', requirement: 300, progress: 0, completed: false, reward: { gold: 1200, research: 15 }, tier: 4 },
  { id: 'animal_products_500', name: 'Production Legend', description: 'Collect 500 animal products', category: 'production', requirement: 500, progress: 0, completed: false, reward: { gold: 2500, research: 25 }, tier: 5 },
  
  { id: 'automation_first', name: 'Automation Begins', description: 'Build your first production building', category: 'automation', requirement: 1, progress: 0, completed: false, reward: { gold: 250 }, tier: 1 },
  { id: 'automation_3', name: 'Mechanical Aid', description: 'Build 3 production buildings', category: 'automation', requirement: 3, progress: 0, completed: false, reward: { gold: 400, research: 5 }, tier: 2 },
  { id: 'automation_7', name: 'Automated Farm', description: 'Build 7 production buildings', category: 'automation', requirement: 7, progress: 0, completed: false, reward: { gold: 800, research: 10 }, tier: 3 },
  { id: 'automation_12', name: 'Industrial Complex', description: 'Build 12 production buildings', category: 'automation', requirement: 12, progress: 0, completed: false, reward: { gold: 1500, research: 18 }, tier: 4 },
  { id: 'automation_20', name: 'Industrial Farm', description: 'Build 20 production buildings', category: 'automation', requirement: 20, progress: 0, completed: false, reward: { gold: 3000, research: 30 }, tier: 5 },
  
  { id: 'diverse_farm', name: 'Diverse Farm', description: 'Plant 6 different crop types', category: 'special', requirement: 6, progress: 0, completed: false, reward: { gold: 500, research: 10 }, tier: 2 },
  { id: 'super_diverse_farm', name: 'Super Diverse Farm', description: 'Plant 12 different crop types', category: 'special', requirement: 12, progress: 0, completed: false, reward: { gold: 1200, research: 20 }, tier: 4 },
  { id: 'master_botanist', name: 'Master Botanist', description: 'Plant 20 different crop types', category: 'special', requirement: 20, progress: 0, completed: false, reward: { gold: 3000, research: 40 }, tier: 6 },
  { id: 'diverse_ranch', name: 'Diverse Ranch', description: 'Own 4 different animal types', category: 'special', requirement: 4, progress: 0, completed: false, reward: { gold: 600, research: 12 }, tier: 2 },
  { id: 'master_breeder', name: 'Master Breeder', description: 'Own 8 different animal types', category: 'special', requirement: 8, progress: 0, completed: false, reward: { gold: 1500, research: 25 }, tier: 4 },
  { id: 'zoological_expert', name: 'Zoological Expert', description: 'Own 12 different animal types', category: 'special', requirement: 12, progress: 0, completed: false, reward: { gold: 3500, research: 45 }, tier: 6 },
  { id: 'empire_builder', name: 'Empire Builder', description: 'Own 10+ buildings', category: 'special', requirement: 10, progress: 0, completed: false, reward: { gold: 2500, research: 30 }, tier: 4 },
  { id: 'mega_empire', name: 'Mega Empire', description: 'Own 20+ buildings', category: 'special', requirement: 20, progress: 0, completed: false, reward: { gold: 6000, research: 60 }, tier: 6 },
  
  { id: 'lucky_first', name: 'Lucky Strike', description: 'Get your first critical harvest', category: 'special', requirement: 1, progress: 0, completed: false, reward: { gold: 250, research: 4 }, tier: 1 },
  { id: 'lucky_10', name: 'Fortune Favors', description: 'Get 10 critical harvests', category: 'special', requirement: 10, progress: 0, completed: false, reward: { gold: 600, research: 10 }, tier: 2 },
  { id: 'lucky_25', name: 'Lucky Streak', description: 'Get 25 critical harvests', category: 'special', requirement: 25, progress: 0, completed: false, reward: { gold: 1000, research: 15 }, tier: 3 },
  { id: 'lucky_50', name: 'Luck Master', description: 'Get 50 critical harvests', category: 'special', requirement: 50, progress: 0, completed: false, reward: { gold: 2000, research: 25 }, tier: 4 },
  { id: 'lucky_100', name: 'Fortune Incarnate', description: 'Get 100 critical harvests', category: 'special', requirement: 100, progress: 0, completed: false, reward: { gold: 5000, research: 50 }, tier: 5 },
  { id: 'lucky_250', name: 'Luck Deity', description: 'Get 250 critical harvests', category: 'special', requirement: 250, progress: 0, completed: false, reward: { gold: 12000, research: 100 }, tier: 6 },
]
