import { Crop, Building, Tech, Achievement, Resources, Animal } from './types'

export const INITIAL_RESOURCES: Resources = {
  gold: 150,
  seeds: 20,
  water: 30,
  fertilizer: 10,
  energy: 100,
  research: 0,
  hay: 10,
  milk: 0,
  eggs: 0,
  wool: 0,
  leather: 0,
  meat: 0,
}

export const CROPS: Crop[] = [
  {
    id: 'wheat',
    name: 'Wheat',
    icon: '🌾',
    description: 'Basic grain crop, fast growing',
    cost: { seeds: 1, water: 2 },
    growTime: 8000,
    yield: { gold: 12, seeds: 1, hay: 2 },
    unlocked: true,
    tier: 1,
    category: 'grain',
  },
  {
    id: 'corn',
    name: 'Corn',
    icon: '🌽',
    description: 'Staple crop with good yield',
    cost: { seeds: 2, water: 3, fertilizer: 1 },
    growTime: 12000,
    yield: { gold: 25, seeds: 2, hay: 3 },
    unlocked: true,
    tier: 1,
    category: 'grain',
  },
  {
    id: 'carrot',
    name: 'Carrot',
    icon: '🥕',
    description: 'Root vegetable, moderate value',
    cost: { seeds: 2, water: 3 },
    growTime: 10000,
    yield: { gold: 18, seeds: 1 },
    unlocked: false,
    requiredTech: 'tech_root_crops',
    tier: 2,
    category: 'vegetable',
  },
  {
    id: 'tomato',
    name: 'Tomato',
    icon: '🍅',
    description: 'Valuable fruit, generates research',
    cost: { seeds: 3, water: 4, fertilizer: 2 },
    growTime: 15000,
    yield: { gold: 40, research: 1 },
    unlocked: false,
    requiredTech: 'tech_tomatoes',
    tier: 2,
    category: 'vegetable',
  },
  {
    id: 'potato',
    name: 'Potato',
    icon: '🥔',
    description: 'High yield root crop',
    cost: { seeds: 3, water: 4, fertilizer: 1 },
    growTime: 14000,
    yield: { gold: 35, seeds: 3 },
    unlocked: false,
    requiredTech: 'tech_root_crops',
    tier: 2,
    category: 'vegetable',
  },
  {
    id: 'strawberry',
    name: 'Strawberry',
    icon: '🍓',
    description: 'Premium berry, high value',
    cost: { seeds: 4, water: 5, fertilizer: 3 },
    growTime: 16000,
    yield: { gold: 60, research: 2 },
    unlocked: false,
    requiredTech: 'tech_berries',
    tier: 3,
    category: 'fruit',
  },
  {
    id: 'grapes',
    name: 'Grapes',
    icon: '🍇',
    description: 'Luxury fruit for wine production',
    cost: { seeds: 5, water: 6, fertilizer: 3, energy: 5 },
    growTime: 22000,
    yield: { gold: 90, research: 3 },
    unlocked: false,
    requiredTech: 'tech_fruit_crops',
    tier: 3,
    category: 'fruit',
  },
  {
    id: 'pumpkin',
    name: 'Pumpkin',
    icon: '🎃',
    description: 'Large specialty crop',
    cost: { seeds: 6, water: 7, fertilizer: 4 },
    growTime: 25000,
    yield: { gold: 110, research: 3, seeds: 2 },
    unlocked: false,
    requiredTech: 'tech_specialty_crops',
    tier: 3,
    category: 'vegetable',
  },
  {
    id: 'watermelon',
    name: 'Watermelon',
    icon: '🍉',
    description: 'Massive fruit, excellent profit',
    cost: { seeds: 7, water: 10, fertilizer: 5 },
    growTime: 28000,
    yield: { gold: 140, research: 4 },
    unlocked: false,
    requiredTech: 'tech_specialty_crops',
    tier: 4,
    category: 'fruit',
  },
  {
    id: 'rice',
    name: 'Rice',
    icon: '🌾',
    description: 'Advanced grain, water intensive',
    cost: { seeds: 5, water: 12, fertilizer: 3 },
    growTime: 20000,
    yield: { gold: 80, seeds: 4, hay: 5 },
    unlocked: false,
    requiredTech: 'tech_advanced_grains',
    tier: 4,
    category: 'grain',
  },
  {
    id: 'coffee',
    name: 'Coffee',
    icon: '☕',
    description: 'Export crop with premium value',
    cost: { seeds: 8, water: 8, fertilizer: 6, energy: 10 },
    growTime: 35000,
    yield: { gold: 200, research: 6 },
    unlocked: false,
    requiredTech: 'tech_export_crops',
    tier: 5,
    category: 'exotic',
  },
  {
    id: 'cocoa',
    name: 'Cocoa',
    icon: '🍫',
    description: 'Chocolate production, very valuable',
    cost: { seeds: 10, water: 9, fertilizer: 7, energy: 12 },
    growTime: 40000,
    yield: { gold: 280, research: 8 },
    unlocked: false,
    requiredTech: 'tech_export_crops',
    tier: 5,
    category: 'exotic',
  },
  {
    id: 'crystal_grain',
    name: 'Crystal Grain',
    icon: '💎',
    description: 'Mystical crop with unmatched value',
    cost: { seeds: 15, water: 15, fertilizer: 15, energy: 30 },
    growTime: 60000,
    yield: { gold: 600, research: 15 },
    unlocked: false,
    requiredTech: 'tech_exotic_crops',
    tier: 6,
    category: 'exotic',
  },
]

export const ANIMALS: Animal[] = [
  {
    id: 'chicken',
    name: 'Chicken',
    icon: '🐔',
    description: 'Produces eggs regularly',
    cost: { gold: 80, hay: 5 },
    feedCost: { hay: 2, water: 1 },
    feedInterval: 20000,
    production: { eggs: 3, gold: 10 },
    productionInterval: 15000,
    unlocked: true,
    tier: 1,
    category: 'poultry',
  },
  {
    id: 'cow',
    name: 'Cow',
    icon: '🐄',
    description: 'Produces milk and leather',
    cost: { gold: 250, hay: 20 },
    feedCost: { hay: 5, water: 3 },
    feedInterval: 30000,
    production: { milk: 5, gold: 25 },
    productionInterval: 25000,
    unlocked: false,
    requiredTech: 'tech_livestock',
    tier: 2,
    category: 'livestock',
  },
  {
    id: 'sheep',
    name: 'Sheep',
    icon: '🐑',
    description: 'Produces wool for textiles',
    cost: { gold: 180, hay: 15 },
    feedCost: { hay: 4, water: 2 },
    feedInterval: 25000,
    production: { wool: 4, gold: 20 },
    productionInterval: 22000,
    unlocked: false,
    requiredTech: 'tech_livestock',
    tier: 2,
    category: 'livestock',
  },
  {
    id: 'pig',
    name: 'Pig',
    icon: '🐷',
    description: 'Fast growing, produces meat',
    cost: { gold: 200, hay: 12 },
    feedCost: { hay: 6, water: 2 },
    feedInterval: 22000,
    production: { meat: 6, gold: 30 },
    productionInterval: 20000,
    unlocked: false,
    requiredTech: 'tech_livestock',
    tier: 2,
    category: 'livestock',
  },
  {
    id: 'goat',
    name: 'Goat',
    icon: '🐐',
    description: 'Produces milk and leather',
    cost: { gold: 150, hay: 10 },
    feedCost: { hay: 3, water: 2 },
    feedInterval: 20000,
    production: { milk: 3, leather: 1, gold: 18 },
    productionInterval: 18000,
    unlocked: false,
    requiredTech: 'tech_advanced_livestock',
    tier: 3,
    category: 'livestock',
  },
  {
    id: 'duck',
    name: 'Duck',
    icon: '🦆',
    description: 'Produces eggs and feathers',
    cost: { gold: 120, hay: 8 },
    feedCost: { hay: 2, water: 2 },
    feedInterval: 18000,
    production: { eggs: 4, gold: 15 },
    productionInterval: 14000,
    unlocked: false,
    requiredTech: 'tech_poultry_expansion',
    tier: 3,
    category: 'poultry',
  },
  {
    id: 'horse',
    name: 'Horse',
    icon: '🐴',
    description: 'Premium livestock, reduces work time',
    cost: { gold: 800, hay: 40, energy: 20 },
    feedCost: { hay: 8, water: 5 },
    feedInterval: 35000,
    production: { gold: 80, leather: 2 },
    productionInterval: 40000,
    unlocked: false,
    requiredTech: 'tech_premium_livestock',
    tier: 4,
    category: 'livestock',
  },
  {
    id: 'llama',
    name: 'Llama',
    icon: '🦙',
    description: 'Exotic, produces premium wool',
    cost: { gold: 600, hay: 30, energy: 15 },
    feedCost: { hay: 6, water: 3 },
    feedInterval: 30000,
    production: { wool: 8, gold: 60 },
    productionInterval: 35000,
    unlocked: false,
    requiredTech: 'tech_exotic_animals',
    tier: 5,
    category: 'exotic',
  },
  {
    id: 'peacock',
    name: 'Peacock',
    icon: '🦚',
    description: 'Rare ornamental bird, high value',
    cost: { gold: 1200, hay: 25, energy: 25 },
    feedCost: { hay: 4, water: 3 },
    feedInterval: 28000,
    production: { gold: 120, research: 5 },
    productionInterval: 32000,
    unlocked: false,
    requiredTech: 'tech_exotic_animals',
    tier: 5,
    category: 'exotic',
  },
]

export const BUILDINGS: Building[] = [
  {
    id: 'well',
    name: 'Well',
    icon: '🪣',
    description: 'Produces water continuously',
    cost: { gold: 50 },
    buildTime: 0,
    production: { water: 4 },
    productionRate: 8000,
    unlocked: true,
    tier: 1,
    category: 'production',
  },
  {
    id: 'windmill',
    name: 'Windmill',
    icon: '🌬️',
    description: 'Generates renewable energy',
    cost: { gold: 120, water: 10 },
    buildTime: 0,
    production: { energy: 8 },
    productionRate: 12000,
    unlocked: false,
    requiredTech: 'tech_windmill',
    tier: 2,
    category: 'production',
  },
  {
    id: 'compost',
    name: 'Compost Heap',
    icon: '♻️',
    description: 'Recycles waste into fertilizer',
    cost: { gold: 80, water: 5 },
    buildTime: 0,
    production: { fertilizer: 2 },
    productionRate: 10000,
    unlocked: false,
    requiredTech: 'tech_composting',
    tier: 2,
    category: 'processing',
  },
  {
    id: 'seed_maker',
    name: 'Seed Maker',
    icon: '🌱',
    description: 'Automatically produces seeds',
    cost: { gold: 150, energy: 15 },
    buildTime: 0,
    production: { seeds: 4 },
    productionRate: 13000,
    unlocked: false,
    requiredTech: 'tech_seed_production',
    tier: 3,
    category: 'production',
  },
  {
    id: 'greenhouse',
    name: 'Greenhouse',
    icon: '🏡',
    description: 'Boosts nearby crop growth by 30%',
    cost: { gold: 250, energy: 25, water: 20 },
    buildTime: 0,
    production: {},
    productionRate: 0,
    unlocked: false,
    requiredTech: 'tech_greenhouse',
    tier: 3,
    category: 'utility',
  },
  {
    id: 'research_lab',
    name: 'Research Lab',
    icon: '🔬',
    description: 'Generates research points for tech',
    cost: { gold: 400, energy: 40 },
    buildTime: 0,
    production: { research: 2 },
    productionRate: 18000,
    unlocked: false,
    requiredTech: 'tech_research',
    tier: 4,
    category: 'production',
  },
  {
    id: 'barn',
    name: 'Barn',
    icon: '🏚️',
    description: 'Stores hay and animal feed',
    cost: { gold: 300, water: 30 },
    buildTime: 0,
    production: { hay: 6 },
    productionRate: 15000,
    unlocked: false,
    requiredTech: 'tech_barn',
    tier: 3,
    category: 'production',
  },
  {
    id: 'dairy',
    name: 'Dairy',
    icon: '🥛',
    description: 'Processes milk into premium goods',
    cost: { gold: 500, energy: 35 },
    buildTime: 0,
    production: { gold: 40 },
    productionRate: 20000,
    unlocked: false,
    requiredTech: 'tech_processing',
    tier: 4,
    category: 'processing',
  },
  {
    id: 'bakery',
    name: 'Bakery',
    icon: '🍞',
    description: 'Converts grain into baked goods',
    cost: { gold: 600, energy: 40 },
    buildTime: 0,
    production: { gold: 50 },
    productionRate: 22000,
    unlocked: false,
    requiredTech: 'tech_processing',
    tier: 4,
    category: 'processing',
  },
  {
    id: 'silo',
    name: 'Storage Silo',
    icon: '🏭',
    description: 'Increases resource storage capacity',
    cost: { gold: 350, water: 20 },
    buildTime: 0,
    production: {},
    productionRate: 0,
    capacity: 1000,
    unlocked: false,
    requiredTech: 'tech_storage',
    tier: 3,
    category: 'utility',
  },
  {
    id: 'solar_panel',
    name: 'Solar Panel',
    icon: '☀️',
    description: 'Advanced energy generation',
    cost: { gold: 800, energy: 50, research: 10 },
    buildTime: 0,
    production: { energy: 20 },
    productionRate: 10000,
    unlocked: false,
    requiredTech: 'tech_solar',
    tier: 5,
    category: 'production',
  },
  {
    id: 'auto_harvester',
    name: 'Auto Harvester',
    icon: '🤖',
    description: 'Automatically harvests nearby mature crops',
    cost: { gold: 1200, energy: 80, research: 15 },
    buildTime: 0,
    production: {},
    productionRate: 0,
    unlocked: false,
    requiredTech: 'tech_automation',
    tier: 5,
    category: 'automation',
  },
  {
    id: 'factory',
    name: 'Processing Factory',
    icon: '🏭',
    description: 'Mass produces advanced goods',
    cost: { gold: 2000, energy: 100, research: 25 },
    buildTime: 0,
    production: { gold: 100, research: 3 },
    productionRate: 25000,
    unlocked: false,
    requiredTech: 'tech_industrialization',
    tier: 6,
    category: 'processing',
  },
]

export const TECH_TREE: Tech[] = [
  {
    id: 'tech_root_crops',
    name: 'Root Vegetables',
    description: 'Unlock carrots and potatoes',
    cost: 5,
    category: 'crops',
    unlocked: true,
    purchased: false,
    prerequisites: [],
    effect: 'unlock_crops',
    tier: 1,
  },
  {
    id: 'tech_tomatoes',
    name: 'Tomato Cultivation',
    description: 'Unlock tomato farming',
    cost: 5,
    category: 'crops',
    unlocked: true,
    purchased: false,
    prerequisites: [],
    effect: 'unlock_crop_tomato',
    tier: 1,
  },
  {
    id: 'tech_berries',
    name: 'Berry Farming',
    description: 'Unlock strawberries and berry crops',
    cost: 10,
    category: 'crops',
    unlocked: true,
    purchased: false,
    prerequisites: [],
    effect: 'unlock_crop_strawberry',
    tier: 2,
  },
  {
    id: 'tech_fruit_crops',
    name: 'Fruit Orchards',
    description: 'Unlock grape vines and orchards',
    cost: 12,
    category: 'crops',
    unlocked: false,
    purchased: false,
    prerequisites: ['tech_berries'],
    effect: 'unlock_crop_grapes',
    tier: 2,
  },
  {
    id: 'tech_specialty_crops',
    name: 'Specialty Crops',
    description: 'Unlock pumpkins and watermelons',
    cost: 15,
    category: 'crops',
    unlocked: false,
    purchased: false,
    prerequisites: ['tech_tomatoes', 'tech_root_crops'],
    effect: 'unlock_specialty',
    tier: 2,
  },
  {
    id: 'tech_advanced_grains',
    name: 'Advanced Grains',
    description: 'Unlock rice and advanced grain crops',
    cost: 20,
    category: 'crops',
    unlocked: false,
    purchased: false,
    prerequisites: ['tech_specialty_crops'],
    effect: 'unlock_crop_rice',
    tier: 3,
  },
  {
    id: 'tech_export_crops',
    name: 'Export Crops',
    description: 'Unlock coffee and cocoa for export',
    cost: 35,
    category: 'crops',
    unlocked: false,
    purchased: false,
    prerequisites: ['tech_fruit_crops', 'tech_advanced_grains'],
    effect: 'unlock_export',
    tier: 4,
  },
  {
    id: 'tech_exotic_crops',
    name: 'Exotic Cultivation',
    description: 'Unlock mystical crystal grain',
    cost: 60,
    category: 'exotic',
    unlocked: false,
    purchased: false,
    prerequisites: ['tech_export_crops'],
    effect: 'unlock_crystal',
    tier: 5,
  },
  {
    id: 'tech_livestock',
    name: 'Animal Husbandry',
    description: 'Unlock cows, sheep, and pigs',
    cost: 8,
    category: 'animals',
    unlocked: true,
    purchased: false,
    prerequisites: [],
    effect: 'unlock_basic_animals',
    tier: 1,
  },
  {
    id: 'tech_advanced_livestock',
    name: 'Advanced Livestock',
    description: 'Unlock goats and improved breeding',
    cost: 15,
    category: 'animals',
    unlocked: false,
    purchased: false,
    prerequisites: ['tech_livestock'],
    effect: 'unlock_goat',
    tier: 2,
  },
  {
    id: 'tech_poultry_expansion',
    name: 'Poultry Expansion',
    description: 'Unlock ducks and advanced poultry',
    cost: 12,
    category: 'animals',
    unlocked: false,
    purchased: false,
    prerequisites: ['tech_livestock'],
    effect: 'unlock_duck',
    tier: 2,
  },
  {
    id: 'tech_premium_livestock',
    name: 'Premium Livestock',
    description: 'Unlock horses for transportation',
    cost: 25,
    category: 'animals',
    unlocked: false,
    purchased: false,
    prerequisites: ['tech_advanced_livestock'],
    effect: 'unlock_horse',
    tier: 3,
  },
  {
    id: 'tech_exotic_animals',
    name: 'Exotic Animals',
    description: 'Unlock llamas and peacocks',
    cost: 40,
    category: 'exotic',
    unlocked: false,
    purchased: false,
    prerequisites: ['tech_premium_livestock', 'tech_poultry_expansion'],
    effect: 'unlock_exotic_animals',
    tier: 4,
  },
  {
    id: 'tech_windmill',
    name: 'Wind Power',
    description: 'Unlock windmill for energy',
    cost: 6,
    category: 'buildings',
    unlocked: true,
    purchased: false,
    prerequisites: [],
    effect: 'unlock_building_windmill',
    tier: 1,
  },
  {
    id: 'tech_composting',
    name: 'Composting',
    description: 'Unlock compost heap for fertilizer',
    cost: 6,
    category: 'buildings',
    unlocked: true,
    purchased: false,
    prerequisites: [],
    effect: 'unlock_building_compost',
    tier: 1,
  },
  {
    id: 'tech_seed_production',
    name: 'Seed Production',
    description: 'Automate seed generation',
    cost: 10,
    category: 'buildings',
    unlocked: false,
    purchased: false,
    prerequisites: ['tech_composting'],
    effect: 'unlock_building_seed_maker',
    tier: 2,
  },
  {
    id: 'tech_greenhouse',
    name: 'Greenhouse Technology',
    description: 'Build greenhouses to boost growth',
    cost: 18,
    category: 'buildings',
    unlocked: false,
    purchased: false,
    prerequisites: ['tech_windmill'],
    effect: 'unlock_building_greenhouse',
    tier: 2,
  },
  {
    id: 'tech_barn',
    name: 'Barn Construction',
    description: 'Build barns for hay storage',
    cost: 15,
    category: 'buildings',
    unlocked: false,
    purchased: false,
    prerequisites: ['tech_livestock'],
    effect: 'unlock_building_barn',
    tier: 2,
  },
  {
    id: 'tech_storage',
    name: 'Advanced Storage',
    description: 'Build silos for bulk storage',
    cost: 20,
    category: 'buildings',
    unlocked: false,
    purchased: false,
    prerequisites: ['tech_seed_production', 'tech_barn'],
    effect: 'unlock_building_storage_silo',
    tier: 3,
  },
  {
    id: 'tech_research',
    name: 'Agricultural Research',
    description: 'Unlock research lab for tech points',
    cost: 25,
    category: 'buildings',
    unlocked: false,
    purchased: false,
    prerequisites: ['tech_greenhouse'],
    effect: 'unlock_building_research_lab',
    tier: 3,
  },
  {
    id: 'tech_processing',
    name: 'Food Processing',
    description: 'Unlock dairy and bakery buildings',
    cost: 30,
    category: 'processing',
    unlocked: false,
    purchased: false,
    prerequisites: ['tech_barn', 'tech_advanced_grains'],
    effect: 'unlock_processing_buildings',
    tier: 3,
  },
  {
    id: 'tech_solar',
    name: 'Solar Energy',
    description: 'Unlock solar panels for clean energy',
    cost: 35,
    category: 'buildings',
    unlocked: false,
    purchased: false,
    prerequisites: ['tech_research'],
    effect: 'unlock_building_solar_panel',
    tier: 4,
  },
  {
    id: 'tech_automation',
    name: 'Farm Automation',
    description: 'Unlock auto-harvesting robots',
    cost: 45,
    category: 'automation',
    unlocked: false,
    purchased: false,
    prerequisites: ['tech_solar'],
    effect: 'unlock_building_auto_harvester',
    tier: 4,
  },
  {
    id: 'tech_industrialization',
    name: 'Industrialization',
    description: 'Unlock mass production factories',
    cost: 70,
    category: 'buildings',
    unlocked: false,
    purchased: false,
    prerequisites: ['tech_automation', 'tech_processing'],
    effect: 'unlock_building_factory',
    tier: 5,
  },
  {
    id: 'tech_faster_growth',
    name: 'Enhanced Growth',
    description: 'Crops grow 15% faster',
    cost: 8,
    category: 'efficiency',
    unlocked: true,
    purchased: false,
    prerequisites: [],
    effect: 'growth_speed_1.15',
    tier: 1,
  },
  {
    id: 'tech_better_yield',
    name: 'Improved Yields',
    description: 'Harvest yields increased by 25%',
    cost: 12,
    category: 'efficiency',
    unlocked: false,
    purchased: false,
    prerequisites: ['tech_faster_growth'],
    effect: 'yield_multiplier_1.25',
    tier: 2,
  },
  {
    id: 'tech_water_efficiency',
    name: 'Water Conservation',
    description: 'Water costs reduced by 30%',
    cost: 10,
    category: 'efficiency',
    unlocked: true,
    purchased: false,
    prerequisites: [],
    effect: 'water_cost_0.70',
    tier: 1,
  },
  {
    id: 'tech_energy_efficiency',
    name: 'Energy Efficiency',
    description: 'Energy production increased by 50%',
    cost: 18,
    category: 'efficiency',
    unlocked: false,
    purchased: false,
    prerequisites: ['tech_water_efficiency', 'tech_windmill'],
    effect: 'energy_production_1.5',
    tier: 2,
  },
  {
    id: 'tech_fertilizer_mastery',
    name: 'Fertilizer Mastery',
    description: 'Fertilizer efficiency improved by 40%',
    cost: 15,
    category: 'efficiency',
    unlocked: false,
    purchased: false,
    prerequisites: ['tech_composting'],
    effect: 'fertilizer_efficiency_1.4',
    tier: 2,
  },
  {
    id: 'tech_animal_care',
    name: 'Animal Care',
    description: 'Animal production increased by 30%',
    cost: 20,
    category: 'efficiency',
    unlocked: false,
    purchased: false,
    prerequisites: ['tech_livestock'],
    effect: 'animal_production_1.3',
    tier: 2,
  },
  {
    id: 'tech_breeding_program',
    name: 'Breeding Program',
    description: 'Animal yields improved by 50%',
    cost: 35,
    category: 'efficiency',
    unlocked: false,
    purchased: false,
    prerequisites: ['tech_animal_care', 'tech_advanced_livestock'],
    effect: 'animal_yield_1.5',
    tier: 3,
  },
  {
    id: 'tech_crop_rotation',
    name: 'Crop Rotation',
    description: 'All crop yields +20%',
    cost: 25,
    category: 'efficiency',
    unlocked: false,
    purchased: false,
    prerequisites: ['tech_better_yield'],
    effect: 'crop_rotation_1.2',
    tier: 3,
  },
  {
    id: 'tech_master_farmer',
    name: 'Master Farmer',
    description: 'All bonuses increased by 25%',
    cost: 100,
    category: 'efficiency',
    unlocked: false,
    purchased: false,
    prerequisites: ['tech_crop_rotation', 'tech_breeding_program', 'tech_automation'],
    effect: 'master_multiplier_1.25',
    tier: 5,
  },
]

export const ACHIEVEMENTS: Achievement[] = [
  { id: 'first_harvest', name: 'First Harvest', description: 'Harvest your first crop', category: 'harvest', requirement: 1, progress: 0, completed: false, reward: { gold: 50 }, tier: 1 },
  { id: 'harvest_10', name: 'Growing Farm', description: 'Harvest 10 crops', category: 'harvest', requirement: 10, progress: 0, completed: false, reward: { research: 2, gold: 20 }, tier: 1 },
  { id: 'harvest_50', name: 'Productive Farm', description: 'Harvest 50 crops', category: 'harvest', requirement: 50, progress: 0, completed: false, reward: { research: 5, gold: 100 }, tier: 2 },
  { id: 'harvest_100', name: 'Abundant Harvest', description: 'Harvest 100 crops', category: 'harvest', requirement: 100, progress: 0, completed: false, reward: { gold: 300, research: 8 }, tier: 2 },
  { id: 'harvest_500', name: 'Master Harvester', description: 'Harvest 500 crops', category: 'harvest', requirement: 500, progress: 0, completed: false, reward: { gold: 1000, research: 15 }, tier: 3 },
  { id: 'harvest_1000', name: 'Harvest Legend', description: 'Harvest 1000 crops', category: 'harvest', requirement: 1000, progress: 0, completed: false, reward: { gold: 3000, research: 25 }, tier: 4 },
  
  { id: 'wealth_500', name: 'First Fortune', description: 'Earn 500 gold', category: 'wealth', requirement: 500, progress: 0, completed: false, reward: { research: 2 }, tier: 1 },
  { id: 'wealth_2000', name: 'Getting Rich', description: 'Earn 2,000 gold', category: 'wealth', requirement: 2000, progress: 0, completed: false, reward: { research: 5, gold: 100 }, tier: 2 },
  { id: 'wealth_10000', name: 'Wealthy Farmer', description: 'Earn 10,000 gold', category: 'wealth', requirement: 10000, progress: 0, completed: false, reward: { gold: 1000, research: 12 }, tier: 3 },
  { id: 'wealth_50000', name: 'Farm Tycoon', description: 'Earn 50,000 gold', category: 'wealth', requirement: 50000, progress: 0, completed: false, reward: { gold: 3000, research: 20 }, tier: 4 },
  { id: 'wealth_100000', name: 'Agricultural Mogul', description: 'Earn 100,000 gold', category: 'wealth', requirement: 100000, progress: 0, completed: false, reward: { gold: 10000, research: 40 }, tier: 5 },
  
  { id: 'tech_first', name: 'Researcher', description: 'Unlock your first technology', category: 'tech', requirement: 1, progress: 0, completed: false, reward: { research: 2 }, tier: 1 },
  { id: 'tech_5', name: 'Tech Enthusiast', description: 'Unlock 5 technologies', category: 'tech', requirement: 5, progress: 0, completed: false, reward: { gold: 200, research: 5 }, tier: 2 },
  { id: 'tech_15', name: 'Tech Innovator', description: 'Unlock 15 technologies', category: 'tech', requirement: 15, progress: 0, completed: false, reward: { gold: 800, research: 15 }, tier: 3 },
  { id: 'tech_30', name: 'Tech Master', description: 'Unlock 30 technologies', category: 'tech', requirement: 30, progress: 0, completed: false, reward: { gold: 2000, research: 30 }, tier: 4 },
  
  { id: 'first_animal', name: 'Rancher Begin', description: 'Purchase your first animal', category: 'animals', requirement: 1, progress: 0, completed: false, reward: { gold: 100, hay: 10 }, tier: 1 },
  { id: 'animals_5', name: 'Growing Ranch', description: 'Own 5 animals', category: 'animals', requirement: 5, progress: 0, completed: false, reward: { gold: 300, research: 5 }, tier: 2 },
  { id: 'animals_15', name: 'Master Rancher', description: 'Own 15 animals', category: 'animals', requirement: 15, progress: 0, completed: false, reward: { gold: 1000, research: 15 }, tier: 3 },
  
  { id: 'animal_products_50', name: 'Animal Products', description: 'Collect 50 animal products', category: 'production', requirement: 50, progress: 0, completed: false, reward: { gold: 200 }, tier: 2 },
  { id: 'animal_products_200', name: 'Production Master', description: 'Collect 200 animal products', category: 'production', requirement: 200, progress: 0, completed: false, reward: { gold: 800, research: 10 }, tier: 3 },
  
  { id: 'automation_first', name: 'Automation Begins', description: 'Build your first production building', category: 'automation', requirement: 1, progress: 0, completed: false, reward: { gold: 200 }, tier: 1 },
  { id: 'automation_5', name: 'Automated Farm', description: 'Build 5 production buildings', category: 'automation', requirement: 5, progress: 0, completed: false, reward: { gold: 500, research: 8 }, tier: 2 },
  { id: 'automation_15', name: 'Industrial Farm', description: 'Build 15 production buildings', category: 'automation', requirement: 15, progress: 0, completed: false, reward: { gold: 1500, research: 20 }, tier: 3 },
  
  { id: 'diverse_farm', name: 'Diverse Farm', description: 'Plant 6 different crop types', category: 'special', requirement: 6, progress: 0, completed: false, reward: { gold: 400, research: 8 }, tier: 2 },
  { id: 'diverse_ranch', name: 'Diverse Ranch', description: 'Own 4 different animal types', category: 'special', requirement: 4, progress: 0, completed: false, reward: { gold: 500, research: 10 }, tier: 2 },
  { id: 'empire_builder', name: 'Empire Builder', description: 'Own 10+ buildings', category: 'special', requirement: 10, progress: 0, completed: false, reward: { gold: 2000, research: 25 }, tier: 4 },
]
