import { Crop, Building, Tech, Achievement, Resources } from './types'

export const INITIAL_RESOURCES: Resources = {
  gold: 100,
  seeds: 10,
  water: 20,
  fertilizer: 5,
  energy: 50,
  research: 0,
}

export const CROPS: Crop[] = [
  {
    id: 'wheat',
    name: 'Wheat',
    icon: '🌾',
    cost: { seeds: 1, water: 2 },
    growTime: 10000,
    yield: { gold: 15, seeds: 1 },
    unlocked: true,
  },
  {
    id: 'corn',
    name: 'Corn',
    icon: '🌽',
    cost: { seeds: 2, water: 3, fertilizer: 1 },
    growTime: 15000,
    yield: { gold: 30, seeds: 2 },
    unlocked: true,
  },
  {
    id: 'tomato',
    name: 'Tomato',
    icon: '🍅',
    cost: { seeds: 3, water: 4, fertilizer: 2 },
    growTime: 20000,
    yield: { gold: 50, research: 1 },
    unlocked: false,
    requiredTech: 'tech_tomatoes',
  },
  {
    id: 'carrot',
    name: 'Carrot',
    icon: '🥕',
    cost: { seeds: 2, water: 3 },
    growTime: 12000,
    yield: { gold: 20, seeds: 2 },
    unlocked: false,
    requiredTech: 'tech_root_crops',
  },
  {
    id: 'pumpkin',
    name: 'Pumpkin',
    icon: '🎃',
    cost: { seeds: 5, water: 6, fertilizer: 3 },
    growTime: 30000,
    yield: { gold: 100, research: 3 },
    unlocked: false,
    requiredTech: 'tech_specialty_crops',
  },
  {
    id: 'grapes',
    name: 'Grapes',
    icon: '🍇',
    cost: { seeds: 4, water: 5, fertilizer: 2, energy: 5 },
    growTime: 25000,
    yield: { gold: 80, research: 2 },
    unlocked: false,
    requiredTech: 'tech_fruit_crops',
  },
  {
    id: 'strawberry',
    name: 'Strawberry',
    icon: '🍓',
    cost: { seeds: 3, water: 4, fertilizer: 2 },
    growTime: 18000,
    yield: { gold: 60, research: 2 },
    unlocked: false,
    requiredTech: 'tech_berries',
  },
  {
    id: 'exotic_crystal',
    name: 'Crystal Grain',
    icon: '💎',
    cost: { seeds: 10, water: 10, fertilizer: 10, energy: 20 },
    growTime: 60000,
    yield: { gold: 500, research: 10 },
    unlocked: false,
    requiredTech: 'tech_exotic_crops',
  },
]

export const BUILDINGS: Building[] = [
  {
    id: 'well',
    name: 'Well',
    icon: '🪣',
    description: 'Produces water over time',
    cost: { gold: 50 },
    buildTime: 5000,
    production: { water: 5 },
    productionRate: 10000,
    unlocked: true,
  },
  {
    id: 'windmill',
    name: 'Windmill',
    icon: '🌬️',
    description: 'Generates energy from wind',
    cost: { gold: 100 },
    buildTime: 8000,
    production: { energy: 10 },
    productionRate: 15000,
    unlocked: false,
    requiredTech: 'tech_windmill',
  },
  {
    id: 'compost',
    name: 'Compost Heap',
    icon: '♻️',
    description: 'Creates fertilizer from waste',
    cost: { gold: 75 },
    buildTime: 6000,
    production: { fertilizer: 3 },
    productionRate: 12000,
    unlocked: false,
    requiredTech: 'tech_composting',
  },
  {
    id: 'greenhouse',
    name: 'Greenhouse',
    icon: '🏡',
    description: 'Reduces crop grow time by 25%',
    cost: { gold: 200, energy: 20 },
    buildTime: 15000,
    production: {},
    productionRate: 0,
    unlocked: false,
    requiredTech: 'tech_greenhouse',
  },
  {
    id: 'research_lab',
    name: 'Research Lab',
    icon: '🔬',
    description: 'Generates research points',
    cost: { gold: 300, energy: 30 },
    buildTime: 20000,
    production: { research: 2 },
    productionRate: 20000,
    unlocked: false,
    requiredTech: 'tech_research',
  },
  {
    id: 'seed_maker',
    name: 'Seed Maker',
    icon: '🌱',
    description: 'Produces seeds automatically',
    cost: { gold: 150, energy: 15 },
    buildTime: 10000,
    production: { seeds: 5 },
    productionRate: 15000,
    unlocked: false,
    requiredTech: 'tech_seed_production',
  },
  {
    id: 'storage_silo',
    name: 'Storage Silo',
    icon: '🏭',
    description: 'Increases storage capacity by 1000',
    cost: { gold: 250 },
    buildTime: 12000,
    production: {},
    productionRate: 0,
    capacity: 1000,
    unlocked: false,
    requiredTech: 'tech_storage',
  },
  {
    id: 'auto_harvester',
    name: 'Auto Harvester',
    icon: '🤖',
    description: 'Automatically harvests nearby crops',
    cost: { gold: 500, energy: 50 },
    buildTime: 25000,
    production: {},
    productionRate: 0,
    unlocked: false,
    requiredTech: 'tech_automation',
  },
]

export const TECH_TREE: Tech[] = [
  {
    id: 'tech_tomatoes',
    name: 'Tomato Cultivation',
    description: 'Unlock tomato crops',
    cost: 5,
    category: 'crops',
    unlocked: true,
    purchased: false,
    prerequisites: [],
    effect: 'unlock_crop_tomato',
    x: 0,
    y: 0,
  },
  {
    id: 'tech_root_crops',
    name: 'Root Vegetables',
    description: 'Unlock carrot and other root crops',
    cost: 5,
    category: 'crops',
    unlocked: true,
    purchased: false,
    prerequisites: [],
    effect: 'unlock_crop_carrot',
    x: 0,
    y: 1,
  },
  {
    id: 'tech_specialty_crops',
    name: 'Specialty Crops',
    description: 'Unlock pumpkins and high-value crops',
    cost: 15,
    category: 'crops',
    unlocked: false,
    purchased: false,
    prerequisites: ['tech_tomatoes'],
    effect: 'unlock_crop_pumpkin',
    x: 1,
    y: 0,
  },
  {
    id: 'tech_fruit_crops',
    name: 'Fruit Orchards',
    description: 'Unlock grape vines',
    cost: 12,
    category: 'crops',
    unlocked: false,
    purchased: false,
    prerequisites: ['tech_tomatoes'],
    effect: 'unlock_crop_grapes',
    x: 1,
    y: 1,
  },
  {
    id: 'tech_berries',
    name: 'Berry Farming',
    description: 'Unlock berry crops',
    cost: 10,
    category: 'crops',
    unlocked: false,
    purchased: false,
    prerequisites: ['tech_root_crops'],
    effect: 'unlock_crop_strawberry',
    x: 1,
    y: 2,
  },
  {
    id: 'tech_exotic_crops',
    name: 'Exotic Cultivation',
    description: 'Unlock rare crystal crops',
    cost: 50,
    category: 'exotic',
    unlocked: false,
    purchased: false,
    prerequisites: ['tech_specialty_crops', 'tech_fruit_crops'],
    effect: 'unlock_crop_exotic_crystal',
    x: 2,
    y: 0,
  },
  {
    id: 'tech_windmill',
    name: 'Wind Power',
    description: 'Unlock windmill buildings',
    cost: 8,
    category: 'buildings',
    unlocked: true,
    purchased: false,
    prerequisites: [],
    effect: 'unlock_building_windmill',
    x: 0,
    y: 3,
  },
  {
    id: 'tech_composting',
    name: 'Composting',
    description: 'Unlock compost heap',
    cost: 6,
    category: 'buildings',
    unlocked: true,
    purchased: false,
    prerequisites: [],
    effect: 'unlock_building_compost',
    x: 0,
    y: 4,
  },
  {
    id: 'tech_greenhouse',
    name: 'Greenhouse Technology',
    description: 'Build greenhouses to speed crop growth',
    cost: 20,
    category: 'buildings',
    unlocked: false,
    purchased: false,
    prerequisites: ['tech_windmill'],
    effect: 'unlock_building_greenhouse',
    x: 1,
    y: 3,
  },
  {
    id: 'tech_research',
    name: 'Agricultural Research',
    description: 'Unlock research lab',
    cost: 25,
    category: 'buildings',
    unlocked: false,
    purchased: false,
    prerequisites: ['tech_greenhouse'],
    effect: 'unlock_building_research_lab',
    x: 2,
    y: 3,
  },
  {
    id: 'tech_seed_production',
    name: 'Seed Production',
    description: 'Automate seed creation',
    cost: 15,
    category: 'buildings',
    unlocked: false,
    purchased: false,
    prerequisites: ['tech_composting'],
    effect: 'unlock_building_seed_maker',
    x: 1,
    y: 4,
  },
  {
    id: 'tech_storage',
    name: 'Advanced Storage',
    description: 'Build storage silos',
    cost: 18,
    category: 'buildings',
    unlocked: false,
    purchased: false,
    prerequisites: ['tech_seed_production'],
    effect: 'unlock_building_storage_silo',
    x: 2,
    y: 4,
  },
  {
    id: 'tech_automation',
    name: 'Farm Automation',
    description: 'Unlock auto-harvesting robots',
    cost: 40,
    category: 'automation',
    unlocked: false,
    purchased: false,
    prerequisites: ['tech_research'],
    effect: 'unlock_building_auto_harvester',
    x: 3,
    y: 3,
  },
  {
    id: 'tech_faster_growth',
    name: 'Enhanced Growth',
    description: '+10% crop growth speed',
    cost: 10,
    category: 'efficiency',
    unlocked: true,
    purchased: false,
    prerequisites: [],
    effect: 'growth_speed_1.1',
    x: 0,
    y: 5,
  },
  {
    id: 'tech_better_yield',
    name: 'Improved Yields',
    description: '+20% harvest yields',
    cost: 15,
    category: 'efficiency',
    unlocked: false,
    purchased: false,
    prerequisites: ['tech_faster_growth'],
    effect: 'yield_multiplier_1.2',
    x: 1,
    y: 5,
  },
  {
    id: 'tech_water_efficiency',
    name: 'Water Conservation',
    description: '-25% water cost for crops',
    cost: 12,
    category: 'efficiency',
    unlocked: true,
    purchased: false,
    prerequisites: [],
    effect: 'water_cost_0.75',
    x: 0,
    y: 6,
  },
  {
    id: 'tech_energy_efficiency',
    name: 'Energy Efficiency',
    description: '+50% energy production',
    cost: 20,
    category: 'efficiency',
    unlocked: false,
    purchased: false,
    prerequisites: ['tech_water_efficiency'],
    effect: 'energy_production_1.5',
    x: 1,
    y: 6,
  },
  {
    id: 'tech_master_farmer',
    name: 'Master Farmer',
    description: 'All bonuses increased by 25%',
    cost: 100,
    category: 'efficiency',
    unlocked: false,
    purchased: false,
    prerequisites: ['tech_better_yield', 'tech_energy_efficiency', 'tech_automation'],
    effect: 'master_multiplier_1.25',
    x: 3,
    y: 5,
  },
]

export const ACHIEVEMENTS: Achievement[] = [
  {
    id: 'first_harvest',
    name: 'First Harvest',
    description: 'Harvest your first crop',
    category: 'harvest',
    requirement: 1,
    progress: 0,
    completed: false,
    reward: { gold: 50 },
  },
  {
    id: 'harvest_10',
    name: 'Growing Farm',
    description: 'Harvest 10 crops',
    category: 'harvest',
    requirement: 10,
    progress: 0,
    completed: false,
    reward: { research: 2 },
  },
  {
    id: 'harvest_100',
    name: 'Abundant Harvest',
    description: 'Harvest 100 crops',
    category: 'harvest',
    requirement: 100,
    progress: 0,
    completed: false,
    reward: { gold: 500, research: 5 },
  },
  {
    id: 'harvest_1000',
    name: 'Master Harvester',
    description: 'Harvest 1000 crops',
    category: 'harvest',
    requirement: 1000,
    progress: 0,
    completed: false,
    reward: { gold: 5000, research: 20 },
  },
  {
    id: 'wealth_1000',
    name: 'Getting Rich',
    description: 'Earn 1000 gold',
    category: 'wealth',
    requirement: 1000,
    progress: 0,
    completed: false,
    reward: { research: 3 },
  },
  {
    id: 'wealth_10000',
    name: 'Wealthy Farmer',
    description: 'Earn 10,000 gold',
    category: 'wealth',
    requirement: 10000,
    progress: 0,
    completed: false,
    reward: { gold: 2000, research: 10 },
  },
  {
    id: 'tech_first',
    name: 'Researcher',
    description: 'Unlock your first technology',
    category: 'tech',
    requirement: 1,
    progress: 0,
    completed: false,
    reward: { research: 2 },
  },
  {
    id: 'tech_10',
    name: 'Tech Innovator',
    description: 'Unlock 10 technologies',
    category: 'tech',
    requirement: 10,
    progress: 0,
    completed: false,
    reward: { gold: 1000, research: 15 },
  },
  {
    id: 'automation_first',
    name: 'Automation Begins',
    description: 'Build your first automation building',
    category: 'automation',
    requirement: 1,
    progress: 0,
    completed: false,
    reward: { gold: 500 },
  },
  {
    id: 'queue_master',
    name: 'Queue Master',
    description: 'Have 10 tasks in queue',
    category: 'automation',
    requirement: 10,
    progress: 0,
    completed: false,
    reward: { research: 5 },
  },
  {
    id: 'diverse_farm',
    name: 'Diverse Farm',
    description: 'Plant 5 different crop types',
    category: 'special',
    requirement: 5,
    progress: 0,
    completed: false,
    reward: { gold: 300, research: 5 },
  },
  {
    id: 'prestige_ready',
    name: 'World Feeder',
    description: 'Produce 1,000,000 total food value',
    category: 'special',
    requirement: 1000000,
    progress: 0,
    completed: false,
    reward: { research: 100 },
  },
]
